//! Backward pass execution for the SDDP training loop.
//!
//! [`run_backward_pass`] sweeps stages in reverse order (`T-2` down to `0`),
//! evaluating the cost-to-go at each trial point collected by the preceding
//! forward pass (via [`ExchangeBuffers`]) under every opening from the fixed
//! opening tree, extracting LP duals to form Benders cut coefficients, and
//! aggregating per-opening outcomes via [`RiskMeasure::aggregate_cut`] to
//! produce one cut per trial point per stage. Each aggregated cut is inserted
//! into the [`FutureCostFunction`].
//!
//! ## Stage indexing convention
//!
//! The backward pass generates a cut **at stage `t`** by solving the LP
//! **at stage `t + 1`** (the successor) under each opening noise vector from
//! that successor stage. The opening tree provides noise at `t + 1`.
//!
//! ## Cut coefficient formula
//!
//! For a solve at stage `t + 1` with trial point state `x_hat`:
//!
//! ```text
//! pi[i]     = -dual[i]                       for i in 0..n_state
//! alpha     = Q - sum_i(pi[i] * x_hat[i])   (intercept)
//! ```
//!
//! where `Q` is the LP objective and `dual[0..n_state]` are the duals of the
//! fixing constraints (storage-fixing and lag-fixing rows).
//!
//! ## Cut activity tracking
//!
//! After each backward solve, the duals of the appended cut rows are inspected
//! to determine which existing cuts at the successor stage are binding. The
//! metadata of binding cuts is updated in-place so that cut selection
//! strategies have accurate activity counts at the end of the iteration.
//!
//! ## Hot-path allocation discipline
//!
//! Allocations are limited to:
//! - One `Vec<f64>` for opening probabilities per stage (outside the trial
//!   point loop).
//! - One `Vec<BackwardOutcome>` pre-allocated before the trial point loop and
//!   reused via `clear()` per trial point.
//! - One `RowBatch` per stage built by [`build_cut_row_batch`] (outside the
//!   trial point loop).
//!
//! No allocations occur inside the inner opening loop.

use std::time::Instant;

use cobre_comm::Communicator;
use cobre_solver::{SolverError, SolverInterface, StageTemplate};
use cobre_stochastic::StochasticContext;

use crate::{
    forward::build_cut_row_batch, risk_measure::BackwardOutcome, risk_measure::RiskMeasure,
    state_exchange::ExchangeBuffers, FutureCostFunction, HorizonMode, PatchBuffer, SddpError,
    StageIndexer, TrainingConfig,
};

/// Result produced by the backward pass on a single rank.
///
/// After the backward pass completes, the calling training loop may inspect
/// these statistics for logging and performance monitoring.
#[derive(Debug, Clone)]
#[must_use]
pub struct BackwardResult {
    /// Total number of cuts generated by this rank during the backward pass.
    ///
    /// In the single-cut formulation, every rank generates cuts for all
    /// `total_scenarios` trial points at every stage. This counter equals
    /// `total_scenarios * (num_stages - 1)`.
    pub cuts_generated: usize,

    /// Wall-clock time in milliseconds for this rank's backward pass.
    ///
    /// Measured from the start of the stage sweep to after the last cut
    /// insertion.
    pub elapsed_ms: u64,
}

/// Execute the backward pass for one training iteration on this rank.
///
/// Sweeps stages from `num_stages - 2` down to `0` (the last stage `T-1` has
/// no successor stage and therefore produces no cuts). For each `(stage,
/// trial_point)` pair, iterates over all openings at the successor stage,
/// solves the LP at the successor stage with the trial point state and the
/// opening noise, extracts duals to form cut coefficients, aggregates
/// per-opening outcomes via the stage-specific [`RiskMeasure`], and inserts
/// the aggregated cut into the FCF at the current stage.
///
/// ## Error handling
///
/// On `SolverError::Infeasible`, returns `SddpError::Infeasible` with the
/// backward stage (0-based), iteration, and global trial point index.
/// On any other `SolverError`, returns `SddpError::Solver`. On error, the
/// FCF may be partially populated.
///
/// # Errors
///
/// Returns `Err(SddpError::Infeasible { .. })` when a stage LP has no
/// feasible solution during the backward sweep. Returns
/// `Err(SddpError::Solver(_))` for all other terminal LP solver failures.
///
/// # Panics (debug builds only)
///
/// Panics if any of the following debug preconditions are violated:
///
/// - `templates.len() != num_stages`
/// - `base_rows.len() != num_stages`
/// - `risk_measures.len() != num_stages`
#[allow(clippy::too_many_arguments)]
#[allow(clippy::too_many_lines)]
pub fn run_backward_pass<S: SolverInterface, C: Communicator>(
    solver: &mut S,
    templates: &[StageTemplate],
    base_rows: &[usize],
    fcf: &mut FutureCostFunction,
    exchange: &ExchangeBuffers,
    stochastic: &StochasticContext,
    config: &TrainingConfig,
    iteration: u64,
    horizon: &HorizonMode,
    risk_measures: &[RiskMeasure],
    patch_buf: &mut PatchBuffer,
    indexer: &StageIndexer,
    comm: &C,
) -> Result<BackwardResult, SddpError> {
    let num_stages = horizon.num_stages();
    let total_scenarios = exchange.total_scenarios();

    debug_assert_eq!(
        templates.len(),
        num_stages,
        "templates.len() {got} != num_stages {expected}",
        got = templates.len(),
        expected = num_stages,
    );
    debug_assert_eq!(
        base_rows.len(),
        num_stages,
        "base_rows.len() {got} != num_stages {expected}",
        got = base_rows.len(),
        expected = num_stages,
    );
    debug_assert_eq!(
        risk_measures.len(),
        num_stages,
        "risk_measures.len() {got} != num_stages {expected}",
        got = risk_measures.len(),
        expected = num_stages,
    );

    let _ = comm;
    let _ = config;

    let start = Instant::now();
    let mut cuts_generated: usize = 0;
    let tree_view = stochastic.tree_view();
    let mut outcomes: Vec<BackwardOutcome> = Vec::new();
    for t in (0..num_stages.saturating_sub(1)).rev() {
        let successor = t + 1;
        let n_openings = tree_view.n_openings(successor);

        #[allow(clippy::cast_precision_loss)]
        let prob = 1.0_f64 / n_openings as f64;
        let probabilities: Vec<f64> = vec![prob; n_openings];

        let cut_batch = build_cut_row_batch(fcf, successor, indexer);
        let num_cuts_at_successor = cut_batch.num_rows;
        let template_num_rows = templates[successor].num_rows;

        if outcomes.capacity() < n_openings {
            outcomes.reserve(n_openings - outcomes.capacity());
        }

        for m in 0..total_scenarios {
            let local_count = exchange.local_count();
            let x_hat = exchange.state_at(m / local_count, m % local_count);

            outcomes.clear();

            for omega in 0..n_openings {
                let noise = tree_view.opening(successor, omega);
                solver.load_model(&templates[successor]);
                solver.add_rows(&cut_batch);

                patch_buf.fill_forward_patches(indexer, x_hat, noise, base_rows[successor]);
                let patch_count = patch_buf.forward_patch_count();
                solver.set_row_bounds(
                    &patch_buf.indices[..patch_count],
                    &patch_buf.lower[..patch_count],
                    &patch_buf.upper[..patch_count],
                );

                let view = solver.solve_view().map_err(|e| match e {
                    SolverError::Infeasible { .. } => SddpError::Infeasible {
                        stage: t,
                        iteration,
                        // m is the global trial point index — cast is safe
                        // because total_scenarios <= usize::MAX.
                        scenario: m,
                    },
                    other => SddpError::Solver(other),
                })?;

                let objective = view.objective;
                let coefficients: Vec<f64> =
                    view.dual[..indexer.n_state].iter().map(|&d| -d).collect();
                let pi_dot_x: f64 = coefficients.iter().zip(x_hat).map(|(pi, x)| pi * x).sum();
                let intercept = objective - pi_dot_x;

                // Collect binding cut slot indices while the view (and its borrow of the
                // solver buffers) is still live. Metadata updates are deferred until
                // after the view is dropped, because those writes go to `fcf` (a
                // separate object), but dropping the view first keeps the code clear.
                let binding_slots: Vec<usize> = if num_cuts_at_successor > 0 {
                    let cut_duals =
                        &view.dual[template_num_rows..template_num_rows + num_cuts_at_successor];
                    fcf.active_cuts(successor)
                        .enumerate()
                        .filter_map(|(cut_idx, (slot, _, _))| {
                            if cut_duals[cut_idx] > 0.0 {
                                Some(slot)
                            } else {
                                None
                            }
                        })
                        .collect()
                } else {
                    Vec::new()
                };
                // view is dropped here; the &mut self borrow on solver is released.

                // Update cut metadata using the collected slot indices.
                for slot in binding_slots {
                    fcf.pools[successor].metadata[slot].active_count += 1;
                    fcf.pools[successor].metadata[slot].last_active_iter = iteration;
                }

                outcomes.push(BackwardOutcome {
                    intercept,
                    coefficients,
                    objective_value: objective,
                });
            }

            let (agg_intercept, agg_coefficients) =
                risk_measures[t].aggregate_cut(&outcomes, &probabilities);

            #[allow(clippy::cast_possible_truncation)]
            let forward_pass_index = m as u32;

            fcf.add_cut(
                t,
                iteration,
                forward_pass_index,
                agg_intercept,
                &agg_coefficients,
            );
            cuts_generated += 1;
        }
    }

    let elapsed_ms = start.elapsed().as_millis();
    #[allow(clippy::cast_possible_truncation)]
    let elapsed_ms_u64 = elapsed_ms as u64;

    Ok(BackwardResult {
        cuts_generated,
        elapsed_ms: elapsed_ms_u64,
    })
}

#[cfg(test)]
mod tests {
    use cobre_comm::{CommData, CommError, Communicator, ReduceOp};
    use cobre_solver::{
        Basis, LpSolution, RowBatch, SolverError, SolverInterface, SolverStatistics, StageTemplate,
    };

    use super::{run_backward_pass, BackwardResult};
    use crate::{
        ExchangeBuffers, FutureCostFunction, HorizonMode, PatchBuffer, RiskMeasure, StageIndexer,
        TrainingConfig, TrajectoryRecord,
    };

    /// Stub communicator for tests (single-rank).
    struct StubComm;

    impl Communicator for StubComm {
        fn allgatherv<T: CommData>(
            &self,
            _send: &[T],
            _recv: &mut [T],
            _counts: &[usize],
            _displs: &[usize],
        ) -> Result<(), CommError> {
            unreachable!("StubComm allgatherv not used in backward pass tests")
        }

        fn allreduce<T: CommData>(
            &self,
            _send: &[T],
            _recv: &mut [T],
            _op: ReduceOp,
        ) -> Result<(), CommError> {
            unreachable!("StubComm allreduce not used in backward pass tests")
        }

        fn broadcast<T: CommData>(&self, _buf: &mut [T], _root: usize) -> Result<(), CommError> {
            unreachable!("StubComm broadcast not used in backward pass tests")
        }

        fn barrier(&self) -> Result<(), CommError> {
            Ok(())
        }

        fn rank(&self) -> usize {
            0
        }

        fn size(&self) -> usize {
            1
        }
    }

    /// Mock solver for testing: returns fixed solution or infeasible error on demand.
    ///
    /// Buffer fields (`buf_primal`, `buf_dual`, `buf_reduced_costs`) store the
    /// solution data that [`SolutionView`] borrows from. They are filled in
    /// `solve_view` before the borrow is established.
    struct MockSolver {
        solution: LpSolution,
        infeasible_at: Option<usize>,
        call_count: usize,
        /// Tracks the current number of rows (template + appended cuts).
        current_num_rows: usize,
        buf_primal: Vec<f64>,
        buf_dual: Vec<f64>,
        buf_reduced_costs: Vec<f64>,
    }

    impl MockSolver {
        fn always_ok(solution: LpSolution) -> Self {
            let base_rows = solution.dual.len();
            let buf_primal = solution.primal.clone();
            let buf_dual = solution.dual.clone();
            let buf_reduced_costs = solution.reduced_costs.clone();
            Self {
                solution,
                infeasible_at: None,
                call_count: 0,
                current_num_rows: base_rows,
                buf_primal,
                buf_dual,
                buf_reduced_costs,
            }
        }

        fn infeasible_on(solution: LpSolution, n: usize) -> Self {
            let base_rows = solution.dual.len();
            let buf_primal = solution.primal.clone();
            let buf_dual = solution.dual.clone();
            let buf_reduced_costs = solution.reduced_costs.clone();
            Self {
                solution,
                infeasible_at: Some(n),
                call_count: 0,
                current_num_rows: base_rows,
                buf_primal,
                buf_dual,
                buf_reduced_costs,
            }
        }
    }

    impl SolverInterface for MockSolver {
        fn load_model(&mut self, template: &StageTemplate) {
            self.current_num_rows = template.num_rows;
        }

        fn add_rows(&mut self, cuts: &RowBatch) {
            self.current_num_rows += cuts.num_rows;
        }

        fn set_row_bounds(&mut self, _indices: &[usize], _lower: &[f64], _upper: &[f64]) {}
        fn set_col_bounds(&mut self, _indices: &[usize], _lower: &[f64], _upper: &[f64]) {}

        fn solve_view(&mut self) -> Result<cobre_solver::SolutionView<'_>, SolverError> {
            let call = self.call_count;
            self.call_count += 1;
            if self.infeasible_at == Some(call) {
                return Err(SolverError::Infeasible { ray: None });
            }
            // Fill internal buffers, resizing dual to match current LP row count.
            self.buf_primal.clone_from(&self.solution.primal);
            self.buf_dual.clone_from(&self.solution.dual);
            self.buf_dual.resize(self.current_num_rows, 0.0);
            self.buf_reduced_costs
                .clone_from(&self.solution.reduced_costs);
            Ok(cobre_solver::SolutionView {
                objective: self.solution.objective,
                primal: &self.buf_primal,
                dual: &self.buf_dual,
                reduced_costs: &self.buf_reduced_costs,
                iterations: self.solution.iterations,
                solve_time_seconds: self.solution.solve_time_seconds,
            })
        }

        fn solve_with_basis_view(
            &mut self,
            _basis: &Basis,
        ) -> Result<cobre_solver::SolutionView<'_>, SolverError> {
            self.solve_view()
        }

        fn reset(&mut self) {}

        fn get_basis(&mut self) -> Basis {
            Basis {
                col_status: vec![],
                row_status: vec![],
            }
        }

        fn statistics(&self) -> SolverStatistics {
            SolverStatistics::default()
        }

        fn name(&self) -> &'static str {
            "Mock"
        }
    }

    fn minimal_template_1_0() -> StageTemplate {
        StageTemplate {
            num_cols: 3,
            num_rows: 1,
            num_nz: 1,
            col_starts: vec![0_i32, 0, 1, 1],
            row_indices: vec![0_i32],
            values: vec![1.0],
            col_lower: vec![0.0, 0.0, 0.0],
            col_upper: vec![f64::INFINITY, f64::INFINITY, f64::INFINITY],
            objective: vec![0.0, 0.0, 1.0],
            row_lower: vec![0.0],
            row_upper: vec![0.0],
            n_state: 1,
            n_transfer: 0,
            n_dual_relevant: 1,
            n_hydro: 1,
            max_par_order: 0,
        }
    }

    fn solution_1_0(objective: f64, dual_storage: f64) -> LpSolution {
        LpSolution {
            objective,
            primal: vec![0.0, 0.0, 0.0],
            dual: vec![dual_storage],
            reduced_costs: vec![0.0; 3],
            iterations: 0,
            solve_time_seconds: 0.0,
        }
    }

    fn exchange_with_states(n_state: usize, states: Vec<Vec<f64>>) -> ExchangeBuffers {
        use cobre_comm::LocalBackend;

        let local_count = states.len();
        let mut bufs = ExchangeBuffers::new(n_state, local_count, 1);
        let records: Vec<TrajectoryRecord> = states
            .into_iter()
            .map(|state| TrajectoryRecord {
                primal: vec![],
                dual: vec![],
                stage_cost: 0.0,
                state,
            })
            .collect();

        let comm = LocalBackend;
        bufs.exchange(&records, 0, 1, &comm).unwrap();
        bufs
    }

    #[allow(clippy::too_many_lines)]
    fn make_stochastic_context(
        n_stages: usize,
        branching_factor: usize,
    ) -> cobre_stochastic::StochasticContext {
        use chrono::NaiveDate;
        use cobre_core::entities::hydro::{Hydro, HydroGenerationModel, HydroPenalties};
        use cobre_core::{
            scenario::{
                CorrelationEntity, CorrelationGroup, CorrelationModel, CorrelationProfile,
                InflowModel,
            },
            temporal::{
                Block, BlockMode, NoiseMethod, ScenarioSourceConfig, Stage, StageRiskConfig,
                StageStateConfig,
            },
            Bus, DeficitSegment, EntityId, SystemBuilder,
        };
        use cobre_stochastic::context::build_stochastic_context;
        use std::collections::BTreeMap;

        let bus = Bus {
            id: EntityId(0),
            name: "B0".to_string(),
            deficit_segments: vec![DeficitSegment {
                depth_mw: None,
                cost_per_mwh: 1000.0,
            }],
            excess_cost: 0.0,
        };
        let hydro = Hydro {
            id: EntityId(1),
            name: "H1".to_string(),
            bus_id: EntityId(0),
            downstream_id: None,
            entry_stage_id: None,
            exit_stage_id: None,
            min_storage_hm3: 0.0,
            max_storage_hm3: 100.0,
            min_outflow_m3s: 0.0,
            max_outflow_m3s: None,
            generation_model: HydroGenerationModel::ConstantProductivity {
                productivity_mw_per_m3s: 1.0,
            },
            min_turbined_m3s: 0.0,
            max_turbined_m3s: 100.0,
            min_generation_mw: 0.0,
            max_generation_mw: 100.0,
            tailrace: None,
            hydraulic_losses: None,
            efficiency: None,
            evaporation_coefficients_mm: None,
            diversion: None,
            filling: None,
            penalties: HydroPenalties {
                spillage_cost: 0.0,
                diversion_cost: 0.0,
                fpha_turbined_cost: 0.0,
                storage_violation_below_cost: 0.0,
                filling_target_violation_cost: 0.0,
                turbined_violation_below_cost: 0.0,
                outflow_violation_below_cost: 0.0,
                outflow_violation_above_cost: 0.0,
                generation_violation_below_cost: 0.0,
                evaporation_violation_cost: 0.0,
                water_withdrawal_violation_cost: 0.0,
            },
        };

        #[allow(clippy::cast_possible_truncation, clippy::cast_possible_wrap)]
        let make_stage = |idx: usize| Stage {
            index: idx,
            id: idx as i32,
            start_date: NaiveDate::from_ymd_opt(2024, 1, 1).unwrap(),
            end_date: NaiveDate::from_ymd_opt(2024, 2, 1).unwrap(),
            season_id: Some(0),
            blocks: vec![Block {
                index: 0,
                name: "S".to_string(),
                duration_hours: 744.0,
            }],
            block_mode: BlockMode::Parallel,
            state_config: StageStateConfig {
                storage: true,
                inflow_lags: false,
            },
            risk_config: StageRiskConfig::Expectation,
            scenario_config: ScenarioSourceConfig {
                branching_factor,
                noise_method: NoiseMethod::Saa,
            },
        };

        let stages: Vec<Stage> = (0..n_stages).map(make_stage).collect();

        #[allow(clippy::cast_possible_truncation)]
        let inflow = |stage_idx: usize| InflowModel {
            hydro_id: EntityId(1),
            #[allow(clippy::cast_possible_truncation, clippy::cast_possible_wrap)]
            stage_id: stage_idx as i32,
            mean_m3s: 100.0,
            std_m3s: 30.0,
            ar_coefficients: vec![],
            residual_std_ratio: 1.0,
        };

        let inflow_models: Vec<InflowModel> = (0..n_stages).map(inflow).collect();

        let mut profiles = BTreeMap::new();
        profiles.insert(
            "default".to_string(),
            CorrelationProfile {
                groups: vec![CorrelationGroup {
                    name: "g1".to_string(),
                    entities: vec![CorrelationEntity {
                        entity_type: "inflow".to_string(),
                        id: EntityId(1),
                    }],
                    matrix: vec![vec![1.0]],
                }],
            },
        );
        let correlation = CorrelationModel {
            method: "cholesky".to_string(),
            profiles,
            schedule: vec![],
        };

        let system = SystemBuilder::new()
            .buses(vec![bus])
            .hydros(vec![hydro])
            .stages(stages)
            .inflow_models(inflow_models)
            .correlation(correlation)
            .build()
            .unwrap();

        build_stochastic_context(&system, 42).unwrap()
    }

    // ── Unit tests ────────────────────────────────────────────────────────────

    #[test]
    fn backward_result_fields_accessible() {
        let r = BackwardResult {
            cuts_generated: 6,
            elapsed_ms: 42,
        };
        assert_eq!(r.cuts_generated, 6);
        assert_eq!(r.elapsed_ms, 42);
    }

    #[test]
    fn backward_result_clone_and_debug() {
        let r = BackwardResult {
            cuts_generated: 3,
            elapsed_ms: 100,
        };
        let c = r.clone();
        assert_eq!(c.cuts_generated, 3);
        let s = format!("{r:?}");
        assert!(s.contains("BackwardResult"));
    }

    #[test]
    fn dual_extraction_formula_coefficients_are_negated_duals() {
        // Given known dual values [d0, d1], coefficients must be [-d0, -d1].
        let d0 = 3.5_f64;
        let d1 = -1.2_f64;
        let dual = [d0, d1];

        let coefficients: Vec<f64> = dual.iter().map(|&d| -d).collect();

        assert!((coefficients[0] - (-d0)).abs() < f64::EPSILON);
        assert!((coefficients[1] - (-d1)).abs() < f64::EPSILON);
    }

    #[test]
    fn intercept_formula_matches_spec() {
        // alpha = Q - pi^T * x_hat
        // Given: objective=50.0, pi=[2.0, -1.0], x_hat=[10.0, 5.0]
        // Expected: alpha = 50.0 - (2.0*10.0 + (-1.0)*5.0) = 50.0 - 15.0 = 35.0
        let objective = 50.0_f64;
        let coefficients = [2.0_f64, -1.0_f64];
        let x_hat = [10.0_f64, 5.0_f64];
        let pi_dot_x: f64 = coefficients
            .iter()
            .zip(x_hat.iter())
            .map(|(p, x)| p * x)
            .sum();
        let intercept = objective - pi_dot_x;
        assert!((intercept - 35.0).abs() < f64::EPSILON);
    }

    #[test]
    fn single_stage_system_produces_no_cuts() {
        // A 1-stage system has no stages with a successor, so the backward
        // sweep (0..0) is empty — zero cuts are generated.
        let stochastic = make_stochastic_context(1, 2);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0()];
        let base_rows = vec![1_usize];

        let n_state = indexer.n_state;
        let forward_passes = 2_u32;
        let mut fcf = FutureCostFunction::new(1, n_state, forward_passes, 10, 0);
        let exchange = exchange_with_states(n_state, vec![vec![10.0], vec![20.0]]);
        let mut patch_buf = PatchBuffer::new(1, 0);
        let config = TrainingConfig {
            forward_passes,
            max_iterations: 10,
            checkpoint_interval: None,
            warm_start_cuts: 0,
            event_sender: None,
        };
        let horizon = HorizonMode::Finite { num_stages: 1 };
        let risk_measures = vec![RiskMeasure::Expectation];

        let solution = solution_1_0(100.0, -5.0);
        let mut solver = MockSolver::always_ok(solution);
        let comm = StubComm;

        let result = run_backward_pass(
            &mut solver,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            &config,
            0,
            &horizon,
            &risk_measures,
            &mut patch_buf,
            &indexer,
            &comm,
        )
        .unwrap();

        assert_eq!(result.cuts_generated, 0);
        assert_eq!(fcf.total_active_cuts(), 0);
    }

    #[test]
    fn two_stage_system_two_trial_points_generates_two_cuts_at_stage_0() {
        // Acceptance criterion: 3-stage system, 1 hydro (n_state=1), 2 openings,
        // 2 trial points → 2 cuts at stage 0. This is the 2-stage version
        // (stages 0 and 1); cuts should exist only at stage 0.
        let n_stages = 2_usize;
        let n_openings = 2_usize;
        let stochastic = make_stochastic_context(n_stages, n_openings);
        let indexer = StageIndexer::new(1, 0); // N=1, L=0
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state; // 1
        let forward_passes = 2_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 10, 0);

        // Two trial points with states [10.0] and [20.0] at stage 0.
        let exchange = exchange_with_states(n_state, vec![vec![10.0], vec![20.0]]);

        let mut patch_buf = PatchBuffer::new(1, 0);
        let config = TrainingConfig {
            forward_passes,
            max_iterations: 10,
            checkpoint_interval: None,
            warm_start_cuts: 0,
            event_sender: None,
        };
        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        // MockSolver returns objective=100.0, dual[0]=-5.0 for every solve.
        // With x_hat=[10.0]: pi=[5.0], alpha = 100 - 5*10 = 50.
        // With x_hat=[20.0]: pi=[5.0], alpha = 100 - 5*20 = 0 (could be negative).
        let solution = solution_1_0(100.0, -5.0);
        let mut solver = MockSolver::always_ok(solution);
        let comm = StubComm;

        let result = run_backward_pass(
            &mut solver,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            &config,
            0,
            &horizon,
            &risk_measures,
            &mut patch_buf,
            &indexer,
            &comm,
        )
        .unwrap();

        // 2 trial points × 1 stage with a successor = 2 cuts at stage 0.
        assert_eq!(result.cuts_generated, 2);
        assert_eq!(fcf.active_cuts(0).count(), 2);
        // Stage 1 (the last stage) gets no cuts.
        assert_eq!(fcf.active_cuts(1).count(), 0);
    }

    #[test]
    fn cut_inserted_with_correct_stage_iteration_and_forward_pass_index() {
        // Acceptance criterion: iteration=2, forward_passes=3, global
        // trial point m=1 → fcf.add_cut(stage=0, iteration=2, fpi=1, ...).
        // slot = warm_start + 2*3 + 1 = 7.
        let n_stages = 2_usize;
        let n_openings = 2_usize;
        let stochastic = make_stochastic_context(n_stages, n_openings);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 3_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 20, 0);

        // 3 trial points (forward_passes=3 on a single rank).
        let exchange = exchange_with_states(n_state, vec![vec![5.0], vec![10.0], vec![15.0]]);

        let mut patch_buf = PatchBuffer::new(1, 0);
        let config = TrainingConfig {
            forward_passes,
            max_iterations: 20,
            checkpoint_interval: None,
            warm_start_cuts: 0,
            event_sender: None,
        };
        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        let solution = solution_1_0(50.0, 0.0);
        let mut solver = MockSolver::always_ok(solution);
        let comm = StubComm;

        let _ = run_backward_pass(
            &mut solver,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            &config,
            2, // iteration=2
            &horizon,
            &risk_measures,
            &mut patch_buf,
            &indexer,
            &comm,
        )
        .unwrap();

        // Trial point m=1: slot = 0 + 2*3 + 1 = 7
        // Verify that pool[0].metadata[7] has the correct iteration and fpi.
        let meta = &fcf.pools[0].metadata[7];
        assert_eq!(meta.iteration_generated, 2);
        assert_eq!(meta.forward_pass_index, 1);
    }

    #[test]
    fn no_cuts_generated_at_last_stage() {
        // Acceptance criterion: 5-stage system → cuts at stages 0..3, not at 4.
        let n_stages = 5_usize;
        let n_openings = 2_usize;
        let stochastic = make_stochastic_context(n_stages, n_openings);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 1_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 10, 0);
        let exchange = exchange_with_states(n_state, vec![vec![10.0]]);

        let mut patch_buf = PatchBuffer::new(1, 0);
        let config = TrainingConfig {
            forward_passes,
            max_iterations: 10,
            checkpoint_interval: None,
            warm_start_cuts: 0,
            event_sender: None,
        };
        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        let solution = solution_1_0(100.0, -3.0);
        let mut solver = MockSolver::always_ok(solution);
        let comm = StubComm;

        let result = run_backward_pass(
            &mut solver,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            &config,
            0,
            &horizon,
            &risk_measures,
            &mut patch_buf,
            &indexer,
            &comm,
        )
        .unwrap();

        // 1 trial point × 4 stages with successors = 4 cuts total.
        assert_eq!(result.cuts_generated, 4);
        for t in 0..4 {
            assert_eq!(fcf.active_cuts(t).count(), 1, "stage {t} should have 1 cut");
        }
        // The last stage (4) must have no cuts.
        assert_eq!(fcf.active_cuts(4).count(), 0, "stage 4 must have no cuts");
    }

    #[test]
    fn elapsed_ms_is_non_negative() {
        let n_stages = 2_usize;
        let stochastic = make_stochastic_context(n_stages, 2);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 1_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 10, 0);
        let exchange = exchange_with_states(n_state, vec![vec![5.0]]);
        let mut patch_buf = PatchBuffer::new(1, 0);
        let config = TrainingConfig {
            forward_passes,
            max_iterations: 10,
            checkpoint_interval: None,
            warm_start_cuts: 0,
            event_sender: None,
        };
        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        let solution = solution_1_0(10.0, 0.0);
        let mut solver = MockSolver::always_ok(solution);
        let comm = StubComm;

        let result = run_backward_pass(
            &mut solver,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            &config,
            0,
            &horizon,
            &risk_measures,
            &mut patch_buf,
            &indexer,
            &comm,
        )
        .unwrap();

        // elapsed_ms is u64, so it is always >= 0.
        let _ = result.elapsed_ms;
    }

    #[test]
    fn infeasible_solver_returns_sddp_infeasible_error() {
        // Acceptance criterion: MockSolver::infeasible_on(0) for the first
        // backward solve → SddpError::Infeasible is returned.
        let n_stages = 2_usize;
        let stochastic = make_stochastic_context(n_stages, 1);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 1_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 10, 0);
        let exchange = exchange_with_states(n_state, vec![vec![10.0]]);
        let mut patch_buf = PatchBuffer::new(1, 0);
        let config = TrainingConfig {
            forward_passes,
            max_iterations: 10,
            checkpoint_interval: None,
            warm_start_cuts: 0,
            event_sender: None,
        };
        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        let solution = solution_1_0(0.0, 0.0);
        // First solve call returns infeasible.
        let mut solver = MockSolver::infeasible_on(solution, 0);
        let comm = StubComm;

        let result = run_backward_pass(
            &mut solver,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            &config,
            0,
            &horizon,
            &risk_measures,
            &mut patch_buf,
            &indexer,
            &comm,
        );

        assert!(
            matches!(result, Err(crate::SddpError::Infeasible { .. })),
            "expected SddpError::Infeasible, got: {result:?}",
        );
    }

    #[test]
    fn expectation_aggregation_mean_of_per_opening_intercepts() {
        // Given 3 openings with uniform probability 1/3 and per-opening
        // intercepts [10.0, 20.0, 30.0], the aggregated intercept must be 20.0.
        use crate::risk_measure::BackwardOutcome as BO;

        let outcomes = vec![
            BO {
                intercept: 10.0,
                coefficients: vec![],
                objective_value: 10.0,
            },
            BO {
                intercept: 20.0,
                coefficients: vec![],
                objective_value: 20.0,
            },
            BO {
                intercept: 30.0,
                coefficients: vec![],
                objective_value: 30.0,
            },
        ];
        let probs = vec![1.0 / 3.0; 3];
        let (intercept, _) = RiskMeasure::Expectation.aggregate_cut(&outcomes, &probs);
        assert!(
            (intercept - 20.0).abs() < 1e-10,
            "expected 20.0, got {intercept}"
        );
    }

    // ── Integration tests ─────────────────────────────────────────────────────

    #[test]
    fn cut_coefficients_and_intercept_match_dual_extraction_formula() {
        // Integration test: verify that the backward pass uses the correct
        // dual extraction formula by checking cuts in the FCF.
        //
        // Setup: 2-stage, N=1, L=0, 1 opening, 1 trial point.
        //   dual[0] = -3.0 (storage-fixing dual from MockSolver)
        //   objective = 80.0
        //   x_hat = [10.0]
        //
        // Expected:
        //   pi[0] = -dual[0] = 3.0
        //   intercept = 80.0 - 3.0 * 10.0 = 50.0
        //   coefficients = [3.0]
        let n_stages = 2_usize;
        let stochastic = make_stochastic_context(n_stages, 1);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 1_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 10, 0);
        let exchange = exchange_with_states(n_state, vec![vec![10.0]]);

        let mut patch_buf = PatchBuffer::new(1, 0);
        let config = TrainingConfig {
            forward_passes,
            max_iterations: 10,
            checkpoint_interval: None,
            warm_start_cuts: 0,
            event_sender: None,
        };
        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        // dual[0] = -3.0, objective = 80.0
        let solution = solution_1_0(80.0, -3.0);
        let mut solver = MockSolver::always_ok(solution);
        let comm = StubComm;

        let _ = run_backward_pass(
            &mut solver,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            &config,
            0,
            &horizon,
            &risk_measures,
            &mut patch_buf,
            &indexer,
            &comm,
        )
        .unwrap();

        let cuts: Vec<_> = fcf.active_cuts(0).collect();
        assert_eq!(cuts.len(), 1);
        let (_, intercept, coefficients) = &cuts[0];

        assert!(
            (intercept - 50.0).abs() < 1e-10,
            "expected intercept=50.0, got {intercept}"
        );
        assert_eq!(coefficients.len(), 1);
        assert!(
            (coefficients[0] - 3.0).abs() < 1e-10,
            "expected coefficient=3.0, got {}",
            coefficients[0]
        );
    }

    #[test]
    fn single_rank_backward_pass_with_local_backend_produces_correct_fcf() {
        // Integration test with LocalBackend communicator (exercises single-rank path).
        use cobre_comm::LocalBackend;

        let n_stages = 3_usize;
        let n_openings = 2_usize;
        let stochastic = make_stochastic_context(n_stages, n_openings);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 2_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 10, 0);
        let exchange = exchange_with_states(n_state, vec![vec![10.0], vec![20.0]]);

        let mut patch_buf = PatchBuffer::new(1, 0);
        let config = TrainingConfig {
            forward_passes,
            max_iterations: 10,
            checkpoint_interval: None,
            warm_start_cuts: 0,
            event_sender: None,
        };
        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        let solution = solution_1_0(100.0, -5.0);
        let mut solver = MockSolver::always_ok(solution);
        let comm = LocalBackend;

        let result = run_backward_pass(
            &mut solver,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            &config,
            0,
            &horizon,
            &risk_measures,
            &mut patch_buf,
            &indexer,
            &comm,
        )
        .unwrap();

        // 3-stage system: cuts at stages 0 and 1; 2 trial points each.
        // Total cuts = 2 stages × 2 trial points = 4.
        assert_eq!(result.cuts_generated, 4);
        assert_eq!(fcf.active_cuts(0).count(), 2);
        assert_eq!(fcf.active_cuts(1).count(), 2);
        assert_eq!(fcf.active_cuts(2).count(), 0);
    }

    #[test]
    fn forward_pass_index_matches_global_scenario_index() {
        // Acceptance criterion: when a cut is generated for global trial point
        // m=5, then `fcf.add_cut(stage, iteration, 5, ...)` is called with
        // forward_pass_index = m = 5.
        //
        // Setup: iteration=2, forward_passes=6 (6 scenarios on 1 rank), 1 opening.
        // ExchangeBuffers: local_count=6, num_ranks=1, total_scenarios=6.
        // state_at(5/6, 5%6) = state_at(0, 5) — valid.
        //
        // Slot formula: slot = warm_start(0) + 2*6 + 5 = 17.
        // The key invariant: forward_pass_index = m = 5.
        let n_stages = 2_usize;
        let stochastic = make_stochastic_context(n_stages, 1);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 6_u32; // 6 scenarios on a single rank
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 20, 0);

        // 6 trial points (m = 0..5). ExchangeBuffers: local_count=6, num_ranks=1.
        let exchange = exchange_with_states(
            n_state,
            vec![
                vec![1.0],
                vec![2.0],
                vec![3.0],
                vec![4.0],
                vec![5.0],
                vec![6.0],
            ],
        );

        let mut patch_buf = PatchBuffer::new(1, 0);
        let config = TrainingConfig {
            forward_passes,
            max_iterations: 20,
            checkpoint_interval: None,
            warm_start_cuts: 0,
            event_sender: None,
        };
        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        let solution = solution_1_0(50.0, 0.0);
        let mut solver = MockSolver::always_ok(solution);
        let comm = StubComm;

        let _ = run_backward_pass(
            &mut solver,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            &config,
            2, // iteration=2
            &horizon,
            &risk_measures,
            &mut patch_buf,
            &indexer,
            &comm,
        )
        .unwrap();

        // m=5: slot = warm_start(0) + 2*6 + 5 = 17
        // The critical check: forward_pass_index in metadata equals global m=5.
        let meta = &fcf.pools[0].metadata[17];
        assert_eq!(meta.iteration_generated, 2, "iteration_generated must be 2");
        assert_eq!(
            meta.forward_pass_index, 5,
            "forward_pass_index must be 5 (= global m)"
        );
    }
}
