//! Backward pass execution for the SDDP training loop.
//!
//! [`run_backward_pass`] sweeps stages in reverse order (`T-2` down to `0`),
//! evaluating the cost-to-go at each trial point **assigned to this rank**
//! during the forward pass. For each trial point, the backward pass iterates
//! over every opening from the fixed opening tree, extracts LP duals to form
//! Benders cut coefficients, and aggregates per-opening outcomes via
//! [`RiskMeasure::aggregate_cut`] to produce one cut per trial point per
//! stage. Each aggregated cut is inserted into the [`FutureCostFunction`].
//!
//! Although [`ExchangeBuffers`] contains trial points from all ranks (after
//! `allgatherv`), each rank only processes its own forward pass assignments
//! to avoid generating duplicate cuts. Cut synchronization (`allgatherv`)
//! distributes the generated cuts to all ranks after the backward pass.
//!
//! ## Stage indexing convention
//!
//! The backward pass generates a cut **at stage `t`** by solving the LP
//! **at stage `t + 1`** (the successor) under each opening noise vector from
//! that successor stage. The opening tree provides noise at `t + 1`.
//!
//! ## Cut coefficient formula
//!
//! For a solve at stage `t + 1` with trial point state `x_hat`:
//!
//! ```text
//! pi[i]     = -dual[i]                       for i in 0..n_state
//! alpha     = Q - sum_i(pi[i] * x_hat[i])   (intercept)
//! ```
//!
//! where `Q` is the LP objective and `dual[0..n_state]` are the duals of the
//! fixing constraints (storage-fixing and lag-fixing rows).
//!
//! ## Cut activity tracking
//!
//! After each backward solve, the duals of the appended cut rows are inspected
//! to determine which existing cuts at the successor stage are binding. The
//! metadata of binding cuts is updated in-place so that cut selection
//! strategies have accurate activity counts at the end of the iteration.
//!
//! ## Thread-level parallelism
//!
//! Within a rank, the outer per-stage loop remains sequential (stage `t`
//! depends on cuts generated at stage `t+1`). The inner trial-point loop is
//! parallelised across [`SolverWorkspace`] instances using rayon's
//! `par_iter_mut`. Trial points are statically partitioned across workspaces
//! (not rayon default work-stealing) to ensure deterministic assignment.
//!
//! Each worker thread generates cuts into a thread-local [`StagedCut`] buffer
//! rather than directly into the FCF. After the parallel region completes for
//! a stage, the staged cuts are sorted by `trial_point_idx` and inserted into
//! the FCF in that deterministic order. This ensures bit-for-bit identical
//! results regardless of thread count or thread completion order.
//!
//! ## Hot-path allocation discipline
//!
//! Allocations are limited to:
//! - One `Vec<f64>` for opening probabilities per stage (outside the trial
//!   point loop).
//! - One `Vec<BackwardOutcome>` per worker thread, allocated once per stage
//!   in the parallel region and reused via `clear()` per trial point.
//! - One `RowBatch` per stage built by [`build_cut_row_batch`] (outside the
//!   trial point loop, before the parallel region).
//! - One `Vec<StagedCut>` per stage for the merge phase (bounded by
//!   `local_work` entries, each holding one cut and its binding slot list).
//!
//! The `binding_slots` vector inside each [`StagedCut`] is allocated per
//! trial point — a flat buffer optimization is deferred to profiling.

use std::time::Instant;

use cobre_comm::Communicator;
use cobre_solver::{Basis, SolverError, SolverInterface, StageTemplate};
use cobre_stochastic::StochasticContext;
use rayon::iter::{IndexedParallelIterator, IntoParallelRefMutIterator, ParallelIterator};

use crate::{
    forward::{build_cut_row_batch, partition},
    risk_measure::BackwardOutcome,
    risk_measure::RiskMeasure,
    state_exchange::ExchangeBuffers,
    workspace::{BasisStore, SolverWorkspace},
    FutureCostFunction, HorizonMode, SddpError, StageIndexer,
};

/// Result produced by the backward pass on a single rank.
#[derive(Debug, Clone)]
#[must_use]
pub struct BackwardResult {
    /// Total number of cuts generated by this rank during the backward pass.
    pub cuts_generated: usize,

    /// Wall-clock time in milliseconds for this rank's backward pass.
    pub elapsed_ms: u64,

    /// Number of LP solves performed during this backward pass.
    pub lp_solves: u64,
}

/// Per-thread staging buffer for one aggregated cut produced at a single trial
/// point during the parallel backward sweep.
///
/// Each worker thread populates one `StagedCut` per trial point instead of
/// writing directly into the [`FutureCostFunction`]. After the parallel region,
/// staged cuts are sorted by `trial_point_idx` and merged into the FCF in
/// deterministic order regardless of thread completion order.
struct StagedCut {
    /// Local trial-point index within `0..local_work`. Used for deterministic
    /// merge ordering after the parallel region.
    trial_point_idx: usize,

    /// Aggregated cut intercept (result of `RiskMeasure::aggregate_cut`).
    intercept: f64,

    /// Aggregated cut coefficients (length = `n_state`).
    coefficients: Vec<f64>,

    /// Global forward-pass index (`fwd_offset + m`), stored as `u32` for the
    /// FCF slot formula.
    forward_pass_index: u32,

    /// Slots in the successor pool that were binding for at least one opening
    /// during this trial point. These are accumulated across openings within
    /// the worker and applied to FCF metadata in the sequential merge phase.
    ///
    /// Each entry is `(slot_index, active_count_increment)` where
    /// `active_count_increment` is the number of openings in which that cut
    /// was binding. This allows the merge phase to correctly accumulate
    /// activity counts without double-counting.
    binding_increments: Vec<(usize, u64)>,
}

/// Execute the backward pass for one training iteration on this rank.
///
/// Sweeps stages from `num_stages - 2` down to `0` (the last stage `T-1` has
/// no successor stage and therefore produces no cuts). For each stage, the
/// trial-point loop is parallelised across the provided [`SolverWorkspace`]
/// instances using static work partitioning. Each worker generates cut data
/// into a thread-local [`StagedCut`] buffer. After the parallel region, staged
/// cuts are sorted by trial-point index and inserted into the FCF in
/// deterministic order.
///
/// The outer per-stage loop remains sequential: stage `t` depends on cuts
/// inserted at stage `t+1` in the previous iteration of the stage loop.
///
/// ## Error handling
///
/// On `SolverError::Infeasible`, returns `SddpError::Infeasible` with the
/// backward stage (0-based), iteration, and global trial point index.
/// On any other `SolverError`, returns `SddpError::Solver`. On error, the
/// FCF may be partially populated.
///
/// # Errors
///
/// Returns `Err(SddpError::Infeasible { .. })` when a stage LP has no
/// feasible solution during the backward sweep. Returns
/// `Err(SddpError::Solver(_))` for all other terminal LP solver failures.
///
/// # Panics (debug builds only)
///
/// Panics if any of the following debug preconditions are violated:
///
/// - `templates.len() != num_stages`
/// - `base_rows.len() != num_stages`
/// - `risk_measures.len() != num_stages`
#[allow(clippy::too_many_arguments)]
#[allow(clippy::too_many_lines)]
pub fn run_backward_pass<S: SolverInterface + Send, C: Communicator>(
    workspaces: &mut [SolverWorkspace<S>],
    basis_store: &BasisStore,
    templates: &[StageTemplate],
    base_rows: &[usize],
    fcf: &mut FutureCostFunction,
    exchange: &ExchangeBuffers,
    stochastic: &StochasticContext,
    iteration: u64,
    horizon: &HorizonMode,
    risk_measures: &[RiskMeasure],
    indexer: &StageIndexer,
    comm: &C,
    local_work: usize,
    fwd_offset: usize,
    noise_scale: &[f64],
    n_hydros: usize,
) -> Result<BackwardResult, SddpError> {
    let num_stages = horizon.num_stages();
    let my_rank = comm.rank();

    debug_assert_eq!(
        templates.len(),
        num_stages,
        "templates.len() {got} != num_stages {expected}",
        got = templates.len(),
        expected = num_stages,
    );
    debug_assert_eq!(
        base_rows.len(),
        num_stages,
        "base_rows.len() {got} != num_stages {expected}",
        got = base_rows.len(),
        expected = num_stages,
    );
    debug_assert_eq!(
        risk_measures.len(),
        num_stages,
        "risk_measures.len() {got} != num_stages {expected}",
        got = risk_measures.len(),
        expected = num_stages,
    );

    let start = Instant::now();

    // Snapshot solve counts before the backward pass to compute the delta.
    let solves_before: u64 = workspaces
        .iter()
        .map(|ws| ws.solver.statistics().solve_count)
        .sum();

    let mut cuts_generated: usize = 0;
    let tree_view = stochastic.tree_view();
    let n_workers = workspaces.len().max(1);

    for t in (0..num_stages.saturating_sub(1)).rev() {
        let successor = t + 1;
        let n_openings = tree_view.n_openings(successor);

        #[allow(clippy::cast_precision_loss)]
        let probabilities: Vec<f64> = vec![1.0_f64 / n_openings as f64; n_openings];

        // Build the cut row batch for the successor stage before the parallel
        // region. This is a read from FCF which is mutated only in the
        // sequential merge phase between stage iterations.
        let cut_batch = build_cut_row_batch(fcf, successor, indexer);
        let num_cuts_at_successor = cut_batch.num_rows;
        let template_num_rows = templates[successor].num_rows;

        // Collect the active-cut slot indices at the successor stage once,
        // before the parallel region, so all workers share the same read-only
        // view. The cut_batch already embeds the cuts in row order; we need
        // the slot indices for binding-slot tracking.
        let successor_active_slots: Vec<usize> = fcf
            .active_cuts(successor)
            .map(|(slot, _, _)| slot)
            .collect();

        // Parallel trial-point evaluation.
        //
        // Each workspace processes a static partition of `0..local_work`.
        // Workers return `Vec<StagedCut>` on success, or `SddpError` on the
        // first LP failure in their partition. The outer `collect::<Result<_,_>>()`
        // short-circuits on the first error across all workers.
        let worker_staged: Vec<Result<Vec<StagedCut>, SddpError>> = workspaces
            .par_iter_mut()
            .enumerate()
            .map(|(worker_id, ws)| {
                let (start_m, end_m) = partition(local_work, n_workers, worker_id);
                let mut staged: Vec<StagedCut> = Vec::with_capacity(end_m - start_m);
                let mut outcomes: Vec<BackwardOutcome> = Vec::with_capacity(n_openings);
                // Accumulate binding-slot increments keyed by slot index.
                // Re-used across trial points within this worker.
                let mut slot_increments: std::collections::HashMap<usize, u64> =
                    std::collections::HashMap::new();

                for m in start_m..end_m {
                    let x_hat = exchange.state_at(my_rank, m);
                    outcomes.clear();
                    slot_increments.clear();

                    // Worker-local warm-start basis for successive openings
                    // within this trial point. The first opening warm-starts
                    // from the forward pass basis (read from `basis_store`);
                    // subsequent openings warm-start from this local basis.
                    // Discarded after all openings for trial point `m`.
                    let mut working_basis: Option<Basis> = None;

                    for omega in 0..n_openings {
                        let raw_noise = tree_view.opening(successor, omega);
                        ws.solver.load_model(&templates[successor]);
                        ws.solver.add_rows(&cut_batch);

                        // Transform raw η → ζ*base + ζ*σ*η for the water-balance
                        // RHS patch (same transformation as the forward pass).
                        ws.noise_buf.clear();
                        let stage_offset = successor * n_hydros;
                        for (h, &eta) in raw_noise.iter().enumerate().take(n_hydros) {
                            let base_rhs = templates[successor].row_lower[base_rows[successor] + h];
                            ws.noise_buf
                                .push(base_rhs + noise_scale[stage_offset + h] * eta);
                        }

                        ws.patch_buf.fill_forward_patches(
                            indexer,
                            x_hat,
                            &ws.noise_buf,
                            base_rows[successor],
                        );
                        let patch_count = ws.patch_buf.forward_patch_count();
                        ws.solver.set_row_bounds(
                            &ws.patch_buf.indices[..patch_count],
                            &ws.patch_buf.lower[..patch_count],
                            &ws.patch_buf.upper[..patch_count],
                        );

                        // For the first opening, warm-start from the forward
                        // pass basis for this (scenario, successor) pair (read
                        // from the shared read-only basis store). For subsequent
                        // openings, warm-start from the previous opening's basis
                        // stored in the worker-local `working_basis`.
                        let warm_basis: Option<&Basis> = if omega == 0 {
                            basis_store.get(m, successor)
                        } else {
                            working_basis.as_ref()
                        };

                        let view = (if let Some(rb) = warm_basis {
                            ws.solver.solve_with_basis(rb)
                        } else {
                            ws.solver.solve()
                        })
                        .map_err(|e| match e {
                            SolverError::Infeasible => SddpError::Infeasible {
                                stage: t,
                                iteration,
                                scenario: fwd_offset + m,
                            },
                            other => SddpError::Solver(other),
                        })?;

                        let objective = view.objective;
                        let coefficients: Vec<f64> = view.dual[..indexer.n_state].to_vec();
                        let pi_dot_x: f64 =
                            coefficients.iter().zip(x_hat).map(|(pi, x)| pi * x).sum();
                        let intercept = objective - pi_dot_x;

                        // Accumulate binding-slot increments for this opening.
                        if num_cuts_at_successor > 0 {
                            let cut_duals = &view.dual
                                [template_num_rows..template_num_rows + num_cuts_at_successor];
                            for (cut_idx, &slot) in successor_active_slots.iter().enumerate() {
                                if cut_duals[cut_idx] > 0.0 {
                                    *slot_increments.entry(slot).or_insert(0) += 1;
                                }
                            }
                        }

                        // Update the worker-local working basis for the next
                        // opening within this trial point.
                        if let Some(rb) = &mut working_basis {
                            ws.solver.get_basis(rb);
                        } else {
                            let mut rb = Basis::new(
                                templates[successor].num_cols,
                                templates[successor].num_rows,
                            );
                            ws.solver.get_basis(&mut rb);
                            working_basis = Some(rb);
                        }

                        outcomes.push(BackwardOutcome {
                            intercept,
                            coefficients,
                            objective_value: objective,
                        });
                    }
                    // `working_basis` is dropped here; it is not written back
                    // to the basis store — the backward pass only reads from it.

                    let (agg_intercept, agg_coefficients) =
                        risk_measures[t].aggregate_cut(&outcomes, &probabilities);

                    let global_index = fwd_offset + m;
                    debug_assert!(
                        u32::try_from(global_index).is_ok(),
                        "global scenario index overflows u32"
                    );
                    #[allow(clippy::cast_possible_truncation)]
                    let forward_pass_index = global_index as u32;

                    let binding_increments: Vec<(usize, u64)> =
                        slot_increments.iter().map(|(&s, &c)| (s, c)).collect();

                    staged.push(StagedCut {
                        trial_point_idx: m,
                        intercept: agg_intercept,
                        coefficients: agg_coefficients,
                        forward_pass_index,
                        binding_increments,
                    });
                }
                Ok(staged)
            })
            .collect();

        // Flatten worker results, propagating the first error encountered.
        let mut all_staged: Vec<StagedCut> = Vec::with_capacity(local_work);
        for worker_result in worker_staged {
            let worker_cuts = worker_result?;
            all_staged.extend(worker_cuts);
        }

        // Sort by trial_point_idx for deterministic insertion order.
        all_staged.sort_by_key(|c| c.trial_point_idx);

        // Sequential merge: insert cuts and update binding metadata in order.
        for cut in all_staged {
            fcf.add_cut(
                t,
                iteration,
                cut.forward_pass_index,
                cut.intercept,
                &cut.coefficients,
            );
            cuts_generated += 1;

            for (slot, increment) in cut.binding_increments {
                fcf.pools[successor].metadata[slot].active_count += increment;
                fcf.pools[successor].metadata[slot].last_active_iter = iteration;
            }
        }
    }

    #[allow(clippy::cast_possible_truncation)]
    let elapsed_ms = start.elapsed().as_millis() as u64;

    let solves_after: u64 = workspaces
        .iter()
        .map(|ws| ws.solver.statistics().solve_count)
        .sum();
    let lp_solves = solves_after - solves_before;

    Ok(BackwardResult {
        cuts_generated,
        elapsed_ms,
        lp_solves,
    })
}

#[cfg(test)]
mod tests {
    use cobre_comm::{CommData, CommError, Communicator, ReduceOp};
    use cobre_solver::{
        Basis, LpSolution, RowBatch, SolverError, SolverInterface, SolverStatistics, StageTemplate,
    };

    use super::{run_backward_pass, BackwardResult};
    use crate::{
        workspace::{BasisStore, SolverWorkspace},
        ExchangeBuffers, FutureCostFunction, HorizonMode, RiskMeasure, StageIndexer,
        TrajectoryRecord,
    };

    /// Stub communicator for tests (single-rank).
    struct StubComm;

    impl Communicator for StubComm {
        fn allgatherv<T: CommData>(
            &self,
            _send: &[T],
            _recv: &mut [T],
            _counts: &[usize],
            _displs: &[usize],
        ) -> Result<(), CommError> {
            unreachable!("StubComm allgatherv not used in backward pass tests")
        }

        fn allreduce<T: CommData>(
            &self,
            _send: &[T],
            _recv: &mut [T],
            _op: ReduceOp,
        ) -> Result<(), CommError> {
            unreachable!("StubComm allreduce not used in backward pass tests")
        }

        fn broadcast<T: CommData>(&self, _buf: &mut [T], _root: usize) -> Result<(), CommError> {
            unreachable!("StubComm broadcast not used in backward pass tests")
        }

        fn barrier(&self) -> Result<(), CommError> {
            Ok(())
        }

        fn rank(&self) -> usize {
            0
        }

        fn size(&self) -> usize {
            1
        }
    }

    /// Mock solver for testing: returns fixed solution or infeasible error on demand.
    ///
    /// Buffer fields (`buf_primal`, `buf_dual`, `buf_reduced_costs`) store the
    /// solution data that [`SolutionView`] borrows from. They are filled in
    /// `solve` before the borrow is established.
    struct MockSolver {
        solution: LpSolution,
        infeasible_at: Option<usize>,
        call_count: usize,
        /// Tracks the current number of rows (template + appended cuts).
        current_num_rows: usize,
        /// Number of times `solve_with_basis` was called.
        warm_start_calls: usize,
        buf_primal: Vec<f64>,
        buf_dual: Vec<f64>,
        buf_reduced_costs: Vec<f64>,
    }

    impl MockSolver {
        fn always_ok(solution: LpSolution) -> Self {
            let base_rows = solution.dual.len();
            let buf_primal = solution.primal.clone();
            let buf_dual = solution.dual.clone();
            let buf_reduced_costs = solution.reduced_costs.clone();
            Self {
                solution,
                infeasible_at: None,
                call_count: 0,
                current_num_rows: base_rows,
                warm_start_calls: 0,
                buf_primal,
                buf_dual,
                buf_reduced_costs,
            }
        }

        fn infeasible_on(solution: LpSolution, n: usize) -> Self {
            let base_rows = solution.dual.len();
            let buf_primal = solution.primal.clone();
            let buf_dual = solution.dual.clone();
            let buf_reduced_costs = solution.reduced_costs.clone();
            Self {
                solution,
                infeasible_at: Some(n),
                call_count: 0,
                current_num_rows: base_rows,
                warm_start_calls: 0,
                buf_primal,
                buf_dual,
                buf_reduced_costs,
            }
        }
    }

    impl SolverInterface for MockSolver {
        fn load_model(&mut self, template: &StageTemplate) {
            self.current_num_rows = template.num_rows;
        }

        fn add_rows(&mut self, cuts: &RowBatch) {
            self.current_num_rows += cuts.num_rows;
        }

        fn set_row_bounds(&mut self, _indices: &[usize], _lower: &[f64], _upper: &[f64]) {}
        fn set_col_bounds(&mut self, _indices: &[usize], _lower: &[f64], _upper: &[f64]) {}

        fn solve(&mut self) -> Result<cobre_solver::SolutionView<'_>, SolverError> {
            let call = self.call_count;
            self.call_count += 1;
            if self.infeasible_at == Some(call) {
                return Err(SolverError::Infeasible);
            }
            // Fill internal buffers, resizing dual to match current LP row count.
            self.buf_primal.clone_from(&self.solution.primal);
            self.buf_dual.clone_from(&self.solution.dual);
            self.buf_dual.resize(self.current_num_rows, 0.0);
            self.buf_reduced_costs
                .clone_from(&self.solution.reduced_costs);
            Ok(cobre_solver::SolutionView {
                objective: self.solution.objective,
                primal: &self.buf_primal,
                dual: &self.buf_dual,
                reduced_costs: &self.buf_reduced_costs,
                iterations: self.solution.iterations,
                solve_time_seconds: self.solution.solve_time_seconds,
            })
        }

        fn reset(&mut self) {}

        fn get_basis(&mut self, _out: &mut Basis) {}

        fn solve_with_basis(
            &mut self,
            _basis: &Basis,
        ) -> Result<cobre_solver::SolutionView<'_>, SolverError> {
            self.warm_start_calls += 1;
            self.solve()
        }

        fn statistics(&self) -> SolverStatistics {
            SolverStatistics::default()
        }

        fn name(&self) -> &'static str {
            "Mock"
        }
    }

    fn minimal_template_1_0() -> StageTemplate {
        StageTemplate {
            num_cols: 3,
            num_rows: 1,
            num_nz: 1,
            col_starts: vec![0_i32, 0, 1, 1],
            row_indices: vec![0_i32],
            values: vec![1.0],
            col_lower: vec![0.0, 0.0, 0.0],
            col_upper: vec![f64::INFINITY, f64::INFINITY, f64::INFINITY],
            objective: vec![0.0, 0.0, 1.0],
            row_lower: vec![0.0],
            row_upper: vec![0.0],
            n_state: 1,
            n_transfer: 0,
            n_dual_relevant: 1,
            n_hydro: 1,
            max_par_order: 0,
        }
    }

    fn solution_1_0(objective: f64, dual_storage: f64) -> LpSolution {
        LpSolution {
            objective,
            primal: vec![0.0, 0.0, 0.0],
            dual: vec![dual_storage],
            reduced_costs: vec![0.0; 3],
            iterations: 0,
            solve_time_seconds: 0.0,
        }
    }

    /// Wrap a `MockSolver` into a single-element `Vec<SolverWorkspace<MockSolver>>`
    /// for tests that exercise the workspace-based backward-pass API.
    ///
    /// The workspace is sized for `n_hydro=1`, `max_par_order=0`, and `n_state`
    /// state dimensions.
    fn single_workspace(solver: MockSolver, n_state: usize) -> Vec<SolverWorkspace<MockSolver>> {
        use crate::lp_builder::PatchBuffer;
        vec![SolverWorkspace {
            solver,
            patch_buf: PatchBuffer::new(1, 0),
            current_state: Vec::with_capacity(n_state),
            noise_buf: Vec::new(),
            inflow_m3s_buf: Vec::new(),
        }]
    }

    /// Create an empty `BasisStore` for `num_scenarios` scenarios and
    /// `num_stages` stages (all slots `None`).
    fn empty_basis_store(num_scenarios: usize, num_stages: usize) -> BasisStore {
        BasisStore::new(num_scenarios, num_stages)
    }

    /// Create a `BasisStore` with one slot pre-populated at
    /// `[scenario][stage]` with the given `Basis`.
    fn basis_store_with_one(
        num_scenarios: usize,
        num_stages: usize,
        scenario: usize,
        stage: usize,
        basis: Basis,
    ) -> BasisStore {
        let mut store = BasisStore::new(num_scenarios, num_stages);
        *store.get_mut(scenario, stage) = Some(basis);
        store
    }

    fn exchange_with_states(n_state: usize, states: Vec<Vec<f64>>) -> ExchangeBuffers {
        use cobre_comm::LocalBackend;

        let local_count = states.len();
        let mut bufs = ExchangeBuffers::new(n_state, local_count, 1);
        let records: Vec<TrajectoryRecord> = states
            .into_iter()
            .map(|state| TrajectoryRecord {
                primal: vec![],
                dual: vec![],
                stage_cost: 0.0,
                state,
            })
            .collect();

        let comm = LocalBackend;
        bufs.exchange(&records, 0, 1, &comm).unwrap();
        bufs
    }

    #[allow(clippy::too_many_lines)]
    fn make_stochastic_context(
        n_stages: usize,
        branching_factor: usize,
    ) -> cobre_stochastic::StochasticContext {
        use chrono::NaiveDate;
        use cobre_core::entities::hydro::{Hydro, HydroGenerationModel, HydroPenalties};
        use cobre_core::{
            scenario::{
                CorrelationEntity, CorrelationGroup, CorrelationModel, CorrelationProfile,
                InflowModel,
            },
            temporal::{
                Block, BlockMode, NoiseMethod, ScenarioSourceConfig, Stage, StageRiskConfig,
                StageStateConfig,
            },
            Bus, DeficitSegment, EntityId, SystemBuilder,
        };
        use cobre_stochastic::context::build_stochastic_context;
        use std::collections::BTreeMap;

        let bus = Bus {
            id: EntityId(0),
            name: "B0".to_string(),
            deficit_segments: vec![DeficitSegment {
                depth_mw: None,
                cost_per_mwh: 1000.0,
            }],
            excess_cost: 0.0,
        };
        let hydro = Hydro {
            id: EntityId(1),
            name: "H1".to_string(),
            bus_id: EntityId(0),
            downstream_id: None,
            entry_stage_id: None,
            exit_stage_id: None,
            min_storage_hm3: 0.0,
            max_storage_hm3: 100.0,
            min_outflow_m3s: 0.0,
            max_outflow_m3s: None,
            generation_model: HydroGenerationModel::ConstantProductivity {
                productivity_mw_per_m3s: 1.0,
            },
            min_turbined_m3s: 0.0,
            max_turbined_m3s: 100.0,
            min_generation_mw: 0.0,
            max_generation_mw: 100.0,
            tailrace: None,
            hydraulic_losses: None,
            efficiency: None,
            evaporation_coefficients_mm: None,
            diversion: None,
            filling: None,
            penalties: HydroPenalties {
                spillage_cost: 0.0,
                diversion_cost: 0.0,
                fpha_turbined_cost: 0.0,
                storage_violation_below_cost: 0.0,
                filling_target_violation_cost: 0.0,
                turbined_violation_below_cost: 0.0,
                outflow_violation_below_cost: 0.0,
                outflow_violation_above_cost: 0.0,
                generation_violation_below_cost: 0.0,
                evaporation_violation_cost: 0.0,
                water_withdrawal_violation_cost: 0.0,
            },
        };

        #[allow(clippy::cast_possible_truncation, clippy::cast_possible_wrap)]
        let make_stage = |idx: usize| Stage {
            index: idx,
            id: idx as i32,
            start_date: NaiveDate::from_ymd_opt(2024, 1, 1).unwrap(),
            end_date: NaiveDate::from_ymd_opt(2024, 2, 1).unwrap(),
            season_id: Some(0),
            blocks: vec![Block {
                index: 0,
                name: "S".to_string(),
                duration_hours: 744.0,
            }],
            block_mode: BlockMode::Parallel,
            state_config: StageStateConfig {
                storage: true,
                inflow_lags: false,
            },
            risk_config: StageRiskConfig::Expectation,
            scenario_config: ScenarioSourceConfig {
                branching_factor,
                noise_method: NoiseMethod::Saa,
            },
        };

        let stages: Vec<Stage> = (0..n_stages).map(make_stage).collect();

        #[allow(clippy::cast_possible_truncation)]
        let inflow = |stage_idx: usize| InflowModel {
            hydro_id: EntityId(1),
            #[allow(clippy::cast_possible_truncation, clippy::cast_possible_wrap)]
            stage_id: stage_idx as i32,
            mean_m3s: 100.0,
            std_m3s: 30.0,
            ar_coefficients: vec![],
            residual_std_ratio: 1.0,
        };

        let inflow_models: Vec<InflowModel> = (0..n_stages).map(inflow).collect();

        let mut profiles = BTreeMap::new();
        profiles.insert(
            "default".to_string(),
            CorrelationProfile {
                groups: vec![CorrelationGroup {
                    name: "g1".to_string(),
                    entities: vec![CorrelationEntity {
                        entity_type: "inflow".to_string(),
                        id: EntityId(1),
                    }],
                    matrix: vec![vec![1.0]],
                }],
            },
        );
        let correlation = CorrelationModel {
            method: "cholesky".to_string(),
            profiles,
            schedule: vec![],
        };

        let system = SystemBuilder::new()
            .buses(vec![bus])
            .hydros(vec![hydro])
            .stages(stages)
            .inflow_models(inflow_models)
            .correlation(correlation)
            .build()
            .unwrap();

        build_stochastic_context(&system, 42).unwrap()
    }

    // ── Unit tests ────────────────────────────────────────────────────────────

    #[test]
    fn backward_result_fields_accessible() {
        let r = BackwardResult {
            cuts_generated: 6,
            elapsed_ms: 42,
            lp_solves: 0,
        };
        assert_eq!(r.cuts_generated, 6);
        assert_eq!(r.elapsed_ms, 42);
    }

    #[test]
    fn backward_result_clone_and_debug() {
        let r = BackwardResult {
            cuts_generated: 3,
            elapsed_ms: 100,
            lp_solves: 0,
        };
        let c = r.clone();
        assert_eq!(c.cuts_generated, 3);
        let s = format!("{r:?}");
        assert!(s.contains("BackwardResult"));
    }

    #[test]
    fn dual_extraction_formula_coefficients_are_negated_duals() {
        // Given known dual values [d0, d1], coefficients must be [-d0, -d1].
        let d0 = 3.5_f64;
        let d1 = -1.2_f64;
        let dual = [d0, d1];

        let coefficients: Vec<f64> = dual.iter().map(|&d| -d).collect();

        assert!((coefficients[0] - (-d0)).abs() < f64::EPSILON);
        assert!((coefficients[1] - (-d1)).abs() < f64::EPSILON);
    }

    #[test]
    fn intercept_formula_matches_spec() {
        // alpha = Q - pi^T * x_hat
        // Given: objective=50.0, pi=[2.0, -1.0], x_hat=[10.0, 5.0]
        // Expected: alpha = 50.0 - (2.0*10.0 + (-1.0)*5.0) = 50.0 - 15.0 = 35.0
        let objective = 50.0_f64;
        let coefficients = [2.0_f64, -1.0_f64];
        let x_hat = [10.0_f64, 5.0_f64];
        let pi_dot_x: f64 = coefficients
            .iter()
            .zip(x_hat.iter())
            .map(|(p, x)| p * x)
            .sum();
        let intercept = objective - pi_dot_x;
        assert!((intercept - 35.0).abs() < f64::EPSILON);
    }

    #[test]
    fn single_stage_system_produces_no_cuts() {
        // A 1-stage system has no stages with a successor, so the backward
        // sweep (0..0) is empty — zero cuts are generated.
        let stochastic = make_stochastic_context(1, 2);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0()];
        let base_rows = vec![1_usize];

        let n_state = indexer.n_state;
        let n_stages = 1_usize;
        let forward_passes = 2_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 10, 0);
        let exchange = exchange_with_states(n_state, vec![vec![10.0], vec![20.0]]);

        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation];

        let solution = solution_1_0(100.0, -5.0);
        let solver = MockSolver::always_ok(solution);
        let comm = StubComm;
        let mut workspaces = single_workspace(solver, n_state);
        let basis_store = empty_basis_store(exchange.local_count(), n_stages);

        let result = run_backward_pass(
            &mut workspaces,
            &basis_store,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            0,
            &horizon,
            &risk_measures,
            &indexer,
            &comm,
            exchange.local_count(),
            0,
            &[],
            0,
        )
        .unwrap();

        assert_eq!(result.cuts_generated, 0);
        assert_eq!(fcf.total_active_cuts(), 0);
    }

    #[test]
    fn two_stage_system_two_trial_points_generates_two_cuts_at_stage_0() {
        // Acceptance criterion: 3-stage system, 1 hydro (n_state=1), 2 openings,
        // 2 trial points → 2 cuts at stage 0. This is the 2-stage version
        // (stages 0 and 1); cuts should exist only at stage 0.
        let n_stages = 2_usize;
        let n_openings = 2_usize;
        let stochastic = make_stochastic_context(n_stages, n_openings);
        let indexer = StageIndexer::new(1, 0); // N=1, L=0
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state; // 1
        let forward_passes = 2_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 10, 0);

        // Two trial points with states [10.0] and [20.0] at stage 0.
        let exchange = exchange_with_states(n_state, vec![vec![10.0], vec![20.0]]);

        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        // MockSolver returns objective=100.0, dual[0]=-5.0 for every solve.
        // With x_hat=[10.0]: pi=[5.0], alpha = 100 - 5*10 = 50.
        // With x_hat=[20.0]: pi=[5.0], alpha = 100 - 5*20 = 0 (could be negative).
        let solution = solution_1_0(100.0, -5.0);
        let solver = MockSolver::always_ok(solution);
        let comm = StubComm;
        let mut workspaces = single_workspace(solver, n_state);
        let basis_store = empty_basis_store(exchange.local_count(), n_stages);

        let result = run_backward_pass(
            &mut workspaces,
            &basis_store,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            0,
            &horizon,
            &risk_measures,
            &indexer,
            &comm,
            exchange.local_count(),
            0,
            &[],
            0,
        )
        .unwrap();

        // 2 trial points × 1 stage with a successor = 2 cuts at stage 0.
        assert_eq!(result.cuts_generated, 2);
        assert_eq!(fcf.active_cuts(0).count(), 2);
        // Stage 1 (the last stage) gets no cuts.
        assert_eq!(fcf.active_cuts(1).count(), 0);
    }

    #[test]
    fn cut_inserted_with_correct_stage_iteration_and_forward_pass_index() {
        // Acceptance criterion: iteration=2, forward_passes=3, global
        // trial point m=1 → fcf.add_cut(stage=0, iteration=2, fpi=1, ...).
        // slot = warm_start + 2*3 + 1 = 7.
        let n_stages = 2_usize;
        let n_openings = 2_usize;
        let stochastic = make_stochastic_context(n_stages, n_openings);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 3_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 20, 0);

        // 3 trial points (forward_passes=3 on a single rank).
        let exchange = exchange_with_states(n_state, vec![vec![5.0], vec![10.0], vec![15.0]]);

        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        let solution = solution_1_0(50.0, 0.0);
        let solver = MockSolver::always_ok(solution);
        let comm = StubComm;
        let mut workspaces = single_workspace(solver, n_state);
        let basis_store = empty_basis_store(exchange.local_count(), n_stages);

        let _ = run_backward_pass(
            &mut workspaces,
            &basis_store,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            2, // iteration=2
            &horizon,
            &risk_measures,
            &indexer,
            &comm,
            exchange.local_count(),
            0,
            &[],
            0,
        )
        .unwrap();

        // Trial point m=1: slot = 0 + 2*3 + 1 = 7
        // Verify that pool[0].metadata[7] has the correct iteration and fpi.
        let meta = &fcf.pools[0].metadata[7];
        assert_eq!(meta.iteration_generated, 2);
        assert_eq!(meta.forward_pass_index, 1);
    }

    #[test]
    fn no_cuts_generated_at_last_stage() {
        // Acceptance criterion: 5-stage system → cuts at stages 0..3, not at 4.
        let n_stages = 5_usize;
        let n_openings = 2_usize;
        let stochastic = make_stochastic_context(n_stages, n_openings);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 1_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 10, 0);
        let exchange = exchange_with_states(n_state, vec![vec![10.0]]);

        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        let solution = solution_1_0(100.0, -3.0);
        let solver = MockSolver::always_ok(solution);
        let comm = StubComm;
        let mut workspaces = single_workspace(solver, n_state);
        let basis_store = empty_basis_store(exchange.local_count(), n_stages);

        let result = run_backward_pass(
            &mut workspaces,
            &basis_store,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            0,
            &horizon,
            &risk_measures,
            &indexer,
            &comm,
            exchange.local_count(),
            0,
            &[],
            0,
        )
        .unwrap();

        // 1 trial point × 4 stages with successors = 4 cuts total.
        assert_eq!(result.cuts_generated, 4);
        for t in 0..4 {
            assert_eq!(fcf.active_cuts(t).count(), 1, "stage {t} should have 1 cut");
        }
        // The last stage (4) must have no cuts.
        assert_eq!(fcf.active_cuts(4).count(), 0, "stage 4 must have no cuts");
    }

    #[test]
    fn elapsed_ms_is_non_negative() {
        let n_stages = 2_usize;
        let stochastic = make_stochastic_context(n_stages, 2);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 1_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 10, 0);
        let exchange = exchange_with_states(n_state, vec![vec![5.0]]);

        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        let solution = solution_1_0(10.0, 0.0);
        let solver = MockSolver::always_ok(solution);
        let comm = StubComm;
        let mut workspaces = single_workspace(solver, n_state);
        let basis_store = empty_basis_store(exchange.local_count(), n_stages);

        let result = run_backward_pass(
            &mut workspaces,
            &basis_store,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            0,
            &horizon,
            &risk_measures,
            &indexer,
            &comm,
            exchange.local_count(),
            0,
            &[],
            0,
        )
        .unwrap();

        // elapsed_ms is u64, so it is always >= 0.
        let _ = result.elapsed_ms;
    }

    #[test]
    fn infeasible_solver_returns_sddp_infeasible_error() {
        // Acceptance criterion: MockSolver::infeasible_on(0) for the first
        // backward solve → SddpError::Infeasible is returned.
        let n_stages = 2_usize;
        let stochastic = make_stochastic_context(n_stages, 1);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 1_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 10, 0);
        let exchange = exchange_with_states(n_state, vec![vec![10.0]]);

        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        let solution = solution_1_0(0.0, 0.0);
        // First solve call returns infeasible.
        let solver = MockSolver::infeasible_on(solution, 0);
        let comm = StubComm;
        let mut workspaces = single_workspace(solver, n_state);
        let basis_store = empty_basis_store(exchange.local_count(), n_stages);

        let result = run_backward_pass(
            &mut workspaces,
            &basis_store,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            0,
            &horizon,
            &risk_measures,
            &indexer,
            &comm,
            exchange.local_count(),
            0,
            &[],
            0,
        );

        assert!(
            matches!(result, Err(crate::SddpError::Infeasible { .. })),
            "expected SddpError::Infeasible, got: {result:?}",
        );
    }

    #[test]
    fn expectation_aggregation_mean_of_per_opening_intercepts() {
        // Given 3 openings with uniform probability 1/3 and per-opening
        // intercepts [10.0, 20.0, 30.0], the aggregated intercept must be 20.0.
        use crate::risk_measure::BackwardOutcome as BO;

        let outcomes = vec![
            BO {
                intercept: 10.0,
                coefficients: vec![],
                objective_value: 10.0,
            },
            BO {
                intercept: 20.0,
                coefficients: vec![],
                objective_value: 20.0,
            },
            BO {
                intercept: 30.0,
                coefficients: vec![],
                objective_value: 30.0,
            },
        ];
        let probs = vec![1.0 / 3.0; 3];
        let (intercept, _) = RiskMeasure::Expectation.aggregate_cut(&outcomes, &probs);
        assert!(
            (intercept - 20.0).abs() < 1e-10,
            "expected 20.0, got {intercept}"
        );
    }

    // ── Integration tests ─────────────────────────────────────────────────────

    #[test]
    fn cut_coefficients_and_intercept_match_dual_extraction_formula() {
        // Integration test: verify that the backward pass uses the correct
        // dual extraction formula by checking cuts in the FCF.
        //
        // Setup: 2-stage, N=1, L=0, 1 opening, 1 trial point.
        //   dual[0] = -3.0 (storage-fixing dual from MockSolver)
        //   objective = 80.0
        //   x_hat = [10.0]
        //
        // Expected (coefficients = dual, not -dual):
        //   pi[0] = dual[0] = -3.0
        //   intercept = 80.0 - (-3.0) * 10.0 = 110.0
        //   coefficients = [-3.0]
        let n_stages = 2_usize;
        let stochastic = make_stochastic_context(n_stages, 1);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 1_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 10, 0);
        let exchange = exchange_with_states(n_state, vec![vec![10.0]]);

        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        // dual[0] = -3.0, objective = 80.0
        let solution = solution_1_0(80.0, -3.0);
        let solver = MockSolver::always_ok(solution);
        let comm = StubComm;
        let mut workspaces = single_workspace(solver, n_state);
        let basis_store = empty_basis_store(exchange.local_count(), n_stages);

        let _ = run_backward_pass(
            &mut workspaces,
            &basis_store,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            0,
            &horizon,
            &risk_measures,
            &indexer,
            &comm,
            exchange.local_count(),
            0,
            &[],
            0,
        )
        .unwrap();

        let cuts: Vec<_> = fcf.active_cuts(0).collect();
        assert_eq!(cuts.len(), 1);
        let (_, intercept, coefficients) = &cuts[0];

        assert!(
            (intercept - 110.0).abs() < 1e-10,
            "expected intercept=110.0, got {intercept}"
        );
        assert_eq!(coefficients.len(), 1);
        assert!(
            (coefficients[0] - (-3.0)).abs() < 1e-10,
            "expected coefficient=-3.0, got {}",
            coefficients[0]
        );
    }

    #[test]
    fn cut_gradient_sign_physically_correct() {
        // Regression test for the Benders cut sign bug.
        //
        // Physical invariant: more initial storage → lower future cost.
        // The storage-fixing dual π is negative (shadow price of relaxing
        // the fixing constraint increases cost when storage decreases).
        //
        // Correct: coefficient = π < 0, so the cut slope is negative
        //   (more storage → lower cut value → lower theta → lower total cost).
        //
        // Old bug: coefficient = -π > 0, so the cut slope was positive
        //   (more storage → higher cut value → wrong incentive).
        let n_stages = 2_usize;
        let stochastic = make_stochastic_context(n_stages, 1);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 1_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 10, 0);
        let exchange = exchange_with_states(n_state, vec![vec![50.0]]);

        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        // dual[0] = -2.0 (negative: more storage → less cost)
        // objective = 100.0, x_hat = 50.0
        let solution = solution_1_0(100.0, -2.0);
        let solver = MockSolver::always_ok(solution);
        let comm = StubComm;
        let mut workspaces = single_workspace(solver, n_state);
        let basis_store = empty_basis_store(exchange.local_count(), n_stages);

        let _ = run_backward_pass(
            &mut workspaces,
            &basis_store,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            0,
            &horizon,
            &risk_measures,
            &indexer,
            &comm,
            exchange.local_count(),
            0,
            &[],
            0,
        )
        .unwrap();

        let cuts: Vec<_> = fcf.active_cuts(0).collect();
        assert_eq!(cuts.len(), 1, "expected exactly one cut");
        let (_, _intercept, coefficients) = &cuts[0];

        // The coefficient must be negative (same sign as the dual).
        // The old bug would produce +2.0 here instead of -2.0.
        assert!(
            coefficients[0] < 0.0,
            "cut coefficient must be negative (more storage → less future cost), \
             got {} — likely the Benders cut sign bug has been reintroduced",
            coefficients[0]
        );
        assert!(
            (coefficients[0] - (-2.0)).abs() < 1e-10,
            "expected coefficient=-2.0, got {}",
            coefficients[0]
        );
    }

    #[test]
    fn cut_is_tight_at_trial_point() {
        // Regression test: a Benders cut must be tight (exact) at the trial
        // point x̂ where it was generated. That is:
        //   intercept + coefficient * x̂ = Q(x̂)
        // where Q(x̂) = objective value of the subproblem at x̂.
        //
        // The cut equation is: θ ≥ intercept + coefficient * x
        // At x = x̂: θ ≥ Q(x̂) + π'(x̂ - x̂) = Q(x̂)
        //
        // If the sign is wrong (coefficient = -π instead of π), then:
        //   intercept + (-π) * x̂ ≠ Q(x̂) in general
        //
        // This test verifies the tightness property.
        let n_stages = 2_usize;
        let stochastic = make_stochastic_context(n_stages, 1);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 1_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 10, 0);
        let x_hat = 30.0_f64;
        let exchange = exchange_with_states(n_state, vec![vec![x_hat]]);

        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        let q_xhat = 200.0_f64; // subproblem objective at x̂
        let dual_storage = -4.0_f64;
        let solution = solution_1_0(q_xhat, dual_storage);
        let solver = MockSolver::always_ok(solution);
        let comm = StubComm;
        let mut workspaces = single_workspace(solver, n_state);
        let basis_store = empty_basis_store(exchange.local_count(), n_stages);

        let _ = run_backward_pass(
            &mut workspaces,
            &basis_store,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            0,
            &horizon,
            &risk_measures,
            &indexer,
            &comm,
            exchange.local_count(),
            0,
            &[],
            0,
        )
        .unwrap();

        let cuts: Vec<_> = fcf.active_cuts(0).collect();
        assert_eq!(cuts.len(), 1);
        let (_, intercept, coefficients) = &cuts[0];

        // Evaluate the cut at x̂: cut_value = intercept + coeff * x̂
        let cut_at_xhat = intercept + coefficients[0] * x_hat;

        // Must equal Q(x̂) (tightness property)
        assert!(
            (cut_at_xhat - q_xhat).abs() < 1e-10,
            "cut must be tight at trial point: \
             cut_value={cut_at_xhat}, Q(x̂)={q_xhat}, \
             intercept={intercept}, coeff={}, x̂={x_hat}",
            coefficients[0]
        );
    }

    #[test]
    fn single_rank_backward_pass_with_local_backend_produces_correct_fcf() {
        // Integration test with LocalBackend communicator (exercises single-rank path).
        use cobre_comm::LocalBackend;

        let n_stages = 3_usize;
        let n_openings = 2_usize;
        let stochastic = make_stochastic_context(n_stages, n_openings);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 2_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 10, 0);
        let exchange = exchange_with_states(n_state, vec![vec![10.0], vec![20.0]]);

        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        let solution = solution_1_0(100.0, -5.0);
        let solver = MockSolver::always_ok(solution);
        let comm = LocalBackend;
        let mut workspaces = single_workspace(solver, n_state);
        let basis_store = empty_basis_store(exchange.local_count(), n_stages);

        let result = run_backward_pass(
            &mut workspaces,
            &basis_store,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            0,
            &horizon,
            &risk_measures,
            &indexer,
            &comm,
            exchange.local_count(),
            0,
            &[],
            0,
        )
        .unwrap();

        // 3-stage system: cuts at stages 0 and 1; 2 trial points each.
        // Total cuts = 2 stages × 2 trial points = 4.
        assert_eq!(result.cuts_generated, 4);
        assert_eq!(fcf.active_cuts(0).count(), 2);
        assert_eq!(fcf.active_cuts(1).count(), 2);
        assert_eq!(fcf.active_cuts(2).count(), 0);
    }

    #[test]
    fn forward_pass_index_matches_global_scenario_index() {
        // Acceptance criterion: when a cut is generated for global trial point
        // m=5, then `fcf.add_cut(stage, iteration, 5, ...)` is called with
        // forward_pass_index = m = 5.
        //
        // Setup: iteration=2, forward_passes=6 (6 scenarios on 1 rank), 1 opening.
        // ExchangeBuffers: local_count=6, num_ranks=1, total_scenarios=6.
        // state_at(5/6, 5%6) = state_at(0, 5) — valid.
        //
        // Slot formula: slot = warm_start(0) + 2*6 + 5 = 17.
        // The key invariant: forward_pass_index = m = 5.
        let n_stages = 2_usize;
        let stochastic = make_stochastic_context(n_stages, 1);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 6_u32; // 6 scenarios on a single rank
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 20, 0);

        // 6 trial points (m = 0..5). ExchangeBuffers: local_count=6, num_ranks=1.
        let exchange = exchange_with_states(
            n_state,
            vec![
                vec![1.0],
                vec![2.0],
                vec![3.0],
                vec![4.0],
                vec![5.0],
                vec![6.0],
            ],
        );

        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        let solution = solution_1_0(50.0, 0.0);
        let solver = MockSolver::always_ok(solution);
        let comm = StubComm;
        let mut workspaces = single_workspace(solver, n_state);
        let basis_store = empty_basis_store(exchange.local_count(), n_stages);

        let _ = run_backward_pass(
            &mut workspaces,
            &basis_store,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            2, // iteration=2
            &horizon,
            &risk_measures,
            &indexer,
            &comm,
            exchange.local_count(),
            0,
            &[],
            0,
        )
        .unwrap();

        // m=5: slot = warm_start(0) + 2*6 + 5 = 17
        // The critical check: forward_pass_index in metadata equals global m=5.
        let meta = &fcf.pools[0].metadata[17];
        assert_eq!(meta.iteration_generated, 2, "iteration_generated must be 2");
        assert_eq!(
            meta.forward_pass_index, 5,
            "forward_pass_index must be 5 (= global m)"
        );
    }

    // ── Unit tests: warm-start basis caching (backward pass) ──────────────────

    /// Warm-start from a pre-populated forward basis: when `BasisStore` has
    /// `Some(Basis)` at `(scenario=0, stage=1)` before the first backward call,
    /// the first opening at the successor stage must call `solve_with_basis`
    /// rather than `solve`.
    ///
    /// AC: Given a 2-stage system, 1 trial point, 1 opening, with
    /// `basis_store.get(0, 1) = Some(Basis::new(...))` pre-populated,
    /// then `solver.warm_start_calls == 1` after the backward pass.
    #[test]
    fn warm_start_uses_prepopulated_forward_basis() {
        let n_stages = 2_usize;
        let n_openings = 1_usize;
        let stochastic = make_stochastic_context(n_stages, n_openings);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 1_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 10, 0);
        let exchange = exchange_with_states(n_state, vec![vec![10.0]]);

        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        let solution = solution_1_0(100.0, -5.0);
        let solver = MockSolver::always_ok(solution);
        let comm = StubComm;

        // Pre-populate the basis store at (scenario=0, stage=1).
        // This simulates a forward pass having already solved stage 1 and cached its basis.
        let pre_basis = Basis::new(templates[1].num_cols, templates[1].num_rows);
        let mut workspaces = single_workspace(solver, n_state);
        let basis_store = basis_store_with_one(exchange.local_count(), n_stages, 0, 1, pre_basis);

        let _ = run_backward_pass(
            &mut workspaces,
            &basis_store,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            0,
            &horizon,
            &risk_measures,
            &indexer,
            &comm,
            exchange.local_count(),
            0,
            &[],
            0,
        )
        .unwrap();

        let warm_start_calls = workspaces[0].solver.warm_start_calls;
        assert_eq!(
            warm_start_calls, 1,
            "first opening at successor stage must call solve_with_basis \
             when basis_store.get(0, 1) is pre-populated (warm_start_calls == 1, got {warm_start_calls})"
        );
    }

    /// Multi-opening warm-start: given 3 openings at the same successor stage,
    /// the first opening cold-starts (store slot is None), and openings 2 and 3
    /// warm-start from the first opening's basis via `working_basis`.
    ///
    /// AC: Given a 2-stage system, 1 trial point, 3 openings, empty basis cache,
    /// then `solver.warm_start_calls == 2` after the backward pass (openings 2
    /// and 3 warm-start; opening 1 cold-starts).
    #[test]
    fn multi_opening_warm_start_subsequent_openings_use_basis() {
        let n_stages = 2_usize;
        let n_openings = 3_usize;
        let stochastic = make_stochastic_context(n_stages, n_openings);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 1_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 10, 0);
        let exchange = exchange_with_states(n_state, vec![vec![10.0]]);

        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        let solution = solution_1_0(100.0, -5.0);
        let solver = MockSolver::always_ok(solution);
        let comm = StubComm;

        // Start with an empty store — opening 1 must cold-start.
        let mut workspaces = single_workspace(solver, n_state);
        let basis_store = empty_basis_store(exchange.local_count(), n_stages);

        let _ = run_backward_pass(
            &mut workspaces,
            &basis_store,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            0,
            &horizon,
            &risk_measures,
            &indexer,
            &comm,
            exchange.local_count(),
            0,
            &[],
            0,
        )
        .unwrap();

        // Opening 1: cold-start (store slot was None for scenario 0, stage 1).
        // Opening 2: warm-start (working_basis populated by opening 1).
        // Opening 3: warm-start (working_basis updated by opening 2).
        let warm_start_calls = workspaces[0].solver.warm_start_calls;
        assert_eq!(
            warm_start_calls, 2,
            "openings 2 and 3 must call solve_with_basis \
             (warm_start_calls == 2, got {warm_start_calls})"
        );
    }

    /// Error propagation: when a backward solve returns `SolverError::Infeasible`,
    /// the error must propagate as `SddpError::Infeasible`.
    ///
    /// In the new per-scenario design, the backward pass uses a local `working_basis`
    /// variable (not written back to `BasisStore`), so there is no shared cache slot
    /// to check after the error. The test verifies that the error is correctly
    /// propagated regardless of what was in the basis store at entry.
    ///
    /// AC: Given a 2-stage system, 1 opening, `MockSolver` returns infeasible on
    /// call 0, then `run_backward_pass` returns `Err(SddpError::Infeasible { .. })`.
    #[test]
    fn backward_solver_error_propagates() {
        let n_stages = 2_usize;
        let n_openings = 1_usize;
        let stochastic = make_stochastic_context(n_stages, n_openings);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        let forward_passes = 1_u32;
        let mut fcf = FutureCostFunction::new(n_stages, n_state, forward_passes, 10, 0);
        let exchange = exchange_with_states(n_state, vec![vec![10.0]]);

        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];

        let solution = solution_1_0(0.0, 0.0);
        // The first backward solve (call 0) returns infeasible.
        let solver = MockSolver::infeasible_on(solution, 0);
        let comm = StubComm;

        // Pre-populate the store — error should propagate regardless.
        let pre_basis = Basis::new(templates[1].num_cols, templates[1].num_rows);
        let mut workspaces = single_workspace(solver, n_state);
        let basis_store = basis_store_with_one(exchange.local_count(), n_stages, 0, 1, pre_basis);

        let result = run_backward_pass(
            &mut workspaces,
            &basis_store,
            &templates,
            &base_rows,
            &mut fcf,
            &exchange,
            &stochastic,
            0,
            &horizon,
            &risk_measures,
            &indexer,
            &comm,
            exchange.local_count(),
            0,
            &[],
            0,
        );

        assert!(
            matches!(result, Err(crate::SddpError::Infeasible { .. })),
            "expected SddpError::Infeasible, got: {result:?}",
        );
        // The BasisStore is not mutated by the backward pass — the working_basis
        // is a local variable dropped on error. The store slot at (0, 1) remains
        // as it was; this just verifies the store is untouched by an error path.
        assert!(
            basis_store.get(0, 1).is_some(),
            "BasisStore must not be mutated by the backward pass error path"
        );
    }

    // ── New test: parallel cut determinism ────────────────────────────────────

    /// AC: When `run_backward_pass` runs with 1 workspace vs 4 workspaces given
    /// the same input data, the FCF pools contain identical cuts (same intercept,
    /// coefficient vectors, and slot assignments for each trial point).
    #[test]
    #[allow(
        clippy::too_many_lines,
        clippy::cast_possible_truncation,
        clippy::cast_precision_loss
    )]
    fn test_backward_pass_parallel_cut_determinism() {
        use crate::lp_builder::PatchBuffer;

        let n_stages = 3_usize;
        let n_openings = 2_usize;
        let n_trial_points = 8_usize;

        let stochastic = make_stochastic_context(n_stages, n_openings);
        let indexer = StageIndexer::new(1, 0);
        let templates = vec![minimal_template_1_0(); n_stages];
        let base_rows = vec![1_usize; n_stages];

        let n_state = indexer.n_state;
        #[allow(clippy::cast_possible_truncation)]
        let forward_passes = n_trial_points as u32;

        // Build 8 distinct trial-point states.
        let states: Vec<Vec<f64>> = (0..n_trial_points).map(|i| vec![i as f64 + 1.0]).collect();
        let exchange = exchange_with_states(n_state, states);

        let horizon = HorizonMode::Finite {
            num_stages: n_stages,
        };
        let risk_measures = vec![RiskMeasure::Expectation; n_stages];
        let solution = solution_1_0(100.0, -5.0);
        let comm = StubComm;

        // --- Run with 1 workspace ---
        let mut fcf_1 = FutureCostFunction::new(n_stages, n_state, forward_passes, 20, 0);
        let solver_1 = MockSolver::always_ok(solution.clone());
        let mut workspaces_1 = vec![SolverWorkspace {
            solver: solver_1,
            patch_buf: PatchBuffer::new(1, 0),
            current_state: Vec::with_capacity(n_state),
            noise_buf: Vec::new(),
            inflow_m3s_buf: Vec::new(),
        }];
        let basis_store_1 = empty_basis_store(exchange.local_count(), n_stages);
        let _ = run_backward_pass(
            &mut workspaces_1,
            &basis_store_1,
            &templates,
            &base_rows,
            &mut fcf_1,
            &exchange,
            &stochastic,
            0,
            &horizon,
            &risk_measures,
            &indexer,
            &comm,
            exchange.local_count(),
            0,
            &[],
            0,
        )
        .unwrap();

        // --- Run with 4 workspaces ---
        let mut fcf_4 = FutureCostFunction::new(n_stages, n_state, forward_passes, 20, 0);
        let mut workspaces_4: Vec<SolverWorkspace<MockSolver>> = (0..4)
            .map(|_| SolverWorkspace {
                solver: MockSolver::always_ok(solution.clone()),
                patch_buf: PatchBuffer::new(1, 0),
                current_state: Vec::with_capacity(n_state),
                noise_buf: Vec::new(),
                inflow_m3s_buf: Vec::new(),
            })
            .collect();
        let basis_store_4 = empty_basis_store(exchange.local_count(), n_stages);
        let _ = run_backward_pass(
            &mut workspaces_4,
            &basis_store_4,
            &templates,
            &base_rows,
            &mut fcf_4,
            &exchange,
            &stochastic,
            0,
            &horizon,
            &risk_measures,
            &indexer,
            &comm,
            exchange.local_count(),
            0,
            &[],
            0,
        )
        .unwrap();

        // --- Verify identical FCF contents for all non-last stages ---
        for t in 0..(n_stages - 1) {
            let cuts_1: Vec<_> = fcf_1.active_cuts(t).collect();
            let cuts_4: Vec<_> = fcf_4.active_cuts(t).collect();

            assert_eq!(
                cuts_1.len(),
                cuts_4.len(),
                "stage {t}: cut count differs (1 workspace: {}, 4 workspaces: {})",
                cuts_1.len(),
                cuts_4.len()
            );

            for (idx, ((slot_1, intercept_1, coeff_1), (slot_4, intercept_4, coeff_4))) in
                cuts_1.iter().zip(cuts_4.iter()).enumerate()
            {
                assert_eq!(
                    slot_1, slot_4,
                    "stage {t} cut {idx}: slot mismatch ({slot_1} vs {slot_4})"
                );
                assert!(
                    (intercept_1 - intercept_4).abs() < 1e-12,
                    "stage {t} cut {idx}: intercept mismatch ({intercept_1} vs {intercept_4})"
                );
                assert_eq!(
                    coeff_1.len(),
                    coeff_4.len(),
                    "stage {t} cut {idx}: coefficient vector length mismatch"
                );
                for (j, (c1, c4)) in coeff_1.iter().zip(coeff_4.iter()).enumerate() {
                    assert!(
                        (c1 - c4).abs() < 1e-12,
                        "stage {t} cut {idx} coeff[{j}]: {c1} vs {c4}"
                    );
                }
            }
        }

        // Last stage must have no cuts in both.
        assert_eq!(fcf_1.active_cuts(n_stages - 1).count(), 0);
        assert_eq!(fcf_4.active_cuts(n_stages - 1).count(), 0);
    }
}
