#!/usr/bin/env python3
"""Generate the Joe-Kuo Sobol direction numbers as a Rust source file.

Downloads the Joe-Kuo new-joe-kuo-6.21201 direction number file and outputs
``crates/cobre-stochastic/src/tree/sobol_directions.rs`` containing a typed
Rust ``const`` array of ``SobolDirEntry`` values.

Usage::

    # Download from UNSW (may require --no-verify-ssl on some systems):
    python3 scripts/generate_sobol_directions.py

    # Use a pre-downloaded local file:
    python3 scripts/generate_sobol_directions.py --local-file /tmp/new-joe-kuo-6.21201

    # Skip SSL verification (one-time offline tool only):
    python3 scripts/generate_sobol_directions.py --no-verify-ssl

The output file is committed to the repository and must not be edited by hand.
Re-run this script only when upgrading the direction number dataset.

Conventions
-----------
- ``initial_dirs`` stores the raw m_i values exactly as listed in the Joe-Kuo
  file (not left-shifted). The sequence generator in ticket-016 handles the
  shift ``v[j] = m_j << (32 - j)`` when initialising direction vectors.
- Array index 0 → dimension 2 (the first Joe-Kuo entry).
- Entries with degree < 18 zero-pad the unused ``initial_dirs`` slots.
"""

from __future__ import annotations

import argparse
import datetime
import ssl
import sys
import urllib.request
from pathlib import Path

PRIMARY_URL = "https://web.maths.unsw.edu.au/~fkuo/sobol/new-joe-kuo-6.21201"
FALLBACK_URL = "https://web.maths.unsw.edu.au/~fkuo/sobol/joe-kuo-old.1111"

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = (
    REPO_ROOT
    / "crates"
    / "cobre-stochastic"
    / "src"
    / "tree"
    / "qmc_sobol"
    / "sobol_directions.rs"
)

MAX_INITIAL_DIRS = 18


def download_file(url: str, *, verify_ssl: bool = True) -> str:
    """Download *url* and return the response body as a string."""
    print(f"Downloading {url} ...", flush=True)
    ctx: ssl.SSLContext | None = None
    if not verify_ssl:
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
    with urllib.request.urlopen(url, timeout=60, context=ctx) as resp:  # noqa: S310
        raw = resp.read()
    return raw.decode("ascii", errors="replace")


def fetch_direction_numbers(*, verify_ssl: bool = True) -> str:
    """Try the primary URL; fall back to the secondary URL on failure."""
    try:
        return download_file(PRIMARY_URL, verify_ssl=verify_ssl)
    except Exception as exc:
        print(f"Primary URL failed ({exc}); trying fallback ...", flush=True)
    return download_file(FALLBACK_URL, verify_ssl=verify_ssl)


def parse_direction_numbers(text: str) -> list[dict]:
    """Parse the Joe-Kuo direction number file.

    The file format (after a header line) is whitespace-separated columns::

        d   s   a   m_1  m_2  ...  m_s

    where:
    - d  — dimension index (2..21201)
    - s  — degree of the primitive polynomial
    - a  — polynomial coefficient (bit-packed)
    - m_i — initial direction numbers (s values)

    Lines whose first non-whitespace character is a letter are skipped (header
    or comment lines).

    Returns a list of dicts with keys ``d``, ``s``, ``a``, ``m``.
    """
    entries: list[dict] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        # Skip header / comment lines (start with a letter)
        if stripped[0].isalpha():
            continue
        parts = stripped.split()
        if len(parts) < 3:
            continue
        try:
            d = int(parts[0])
            s = int(parts[1])
            a = int(parts[2])
            m = [int(x) for x in parts[3:]]
        except ValueError:
            continue
        entries.append({"d": d, "s": s, "a": a, "m": m})
    return entries


def format_entry(entry: dict) -> str:
    """Format a single ``SobolDirEntry`` struct literal."""
    s = entry["s"]
    a = entry["a"]
    m = entry["m"]

    # Pad to MAX_INITIAL_DIRS elements.
    padded = list(m) + [0] * (MAX_INITIAL_DIRS - len(m))
    assert len(padded) == MAX_INITIAL_DIRS, f"padded length mismatch for d={entry['d']}"

    dirs_str = ", ".join(str(v) for v in padded)
    return f"SobolDirEntry {{ degree: {s}, poly: {a}, initial_dirs: [{dirs_str}] }}"


def generate_rust_source(entries: list[dict], source_url: str) -> str:
    """Render the full Rust source file as a string."""
    today = datetime.date.today().isoformat()
    n = len(entries)

    lines: list[str] = []

    lines.append(f"//! Joe-Kuo 2010 Sobol direction numbers for dimensions 2-{n + 1}.")
    lines.append(
        "//! Auto-generated by `scripts/generate_sobol_directions.py` — do not edit."
    )
    lines.append(f"//! Source: <{source_url}>")
    lines.append(f"//! Generated: {today}")
    lines.append("//!")
    lines.append("//! ## Convention")
    lines.append("//!")
    lines.append(
        "//! `initial_dirs` stores raw `m_i` values as listed in the Joe-Kuo file."
    )
    lines.append(
        "//! The sequence generator applies the left-shift `v[j] = m_j << (32 - j)`"
    )
    lines.append(
        "//! when constructing the direction vectors. Array index 0 is dimension 2."
    )
    lines.append("")
    # Suppress clippy::unreadable_literal: the direction numbers are mathematical
    # constants; underscore separators would add noise without aiding readability.
    # Suppress dead_code: these items are used starting from ticket-016.
    lines.append("#![allow(clippy::unreadable_literal, dead_code)]")
    lines.append("")
    lines.append("/// Direction numbers for one Sobol dimension beyond dimension 1.")
    lines.append("#[derive(Debug, Clone, Copy)]")
    lines.append("pub(crate) struct SobolDirEntry {")
    lines.append("    /// Degree of the primitive polynomial.")
    lines.append("    pub degree: u8,")
    lines.append("    /// Primitive polynomial coefficients (bit-packed).")
    lines.append("    pub poly: u32,")
    lines.append(
        "    /// Initial direction numbers `v[1]..v[degree]`, stored as raw `m_i` values."
    )
    lines.append("    /// Unused slots (beyond `degree`) are zero-padded.")
    lines.append(f"    pub initial_dirs: [u32; {MAX_INITIAL_DIRS}],")
    lines.append("}")
    lines.append("")
    lines.append(f"pub(crate) const SOBOL_MAX_DIM: usize = {n + 1};")
    lines.append("")
    lines.append("#[rustfmt::skip]")
    lines.append(f"pub(crate) static SOBOL_DIRECTIONS: [SobolDirEntry; {n}] = [")

    for entry in entries:
        lines.append(f"    {format_entry(entry)},")

    lines.append("];")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate Joe-Kuo Sobol direction numbers as a Rust source file."
    )
    parser.add_argument(
        "--local-file",
        type=Path,
        default=None,
        metavar="PATH",
        help="Use a pre-downloaded local copy of the Joe-Kuo file instead of downloading.",
    )
    parser.add_argument(
        "--no-verify-ssl",
        action="store_true",
        default=False,
        help="Disable SSL certificate verification when downloading (one-time offline use only).",
    )
    args = parser.parse_args()

    if args.local_file is not None:
        print(f"Reading local file {args.local_file} ...", flush=True)
        text = args.local_file.read_text(encoding="ascii", errors="replace")
    else:
        text = fetch_direction_numbers(verify_ssl=not args.no_verify_ssl)

    entries = parse_direction_numbers(text)

    if not entries:
        print(
            "ERROR: no direction number entries parsed from downloaded file.",
            file=sys.stderr,
        )
        return 1

    print(f"Parsed {len(entries)} direction number entries.")

    # Validate basic expectations.
    first = entries[0]
    if first["d"] != 2 or first["s"] != 1 or first["a"] != 0 or first["m"] != [1]:
        print(
            f"WARNING: first entry does not match expected d=2, s=1, a=0, m=[1]: {first}",
            file=sys.stderr,
        )

    last = entries[-1]
    print(
        f"First entry: d={first['d']}, s={first['s']}, a={first['a']}, m={first['m']}"
    )
    print(
        f"Last entry:  d={last['d']}, s={last['s']}, a={last['a']}, m={last['m'][:4]}..."
    )

    max_degree = max(e["s"] for e in entries)
    print(f"Maximum degree: {max_degree} (array slot size: {MAX_INITIAL_DIRS})")
    if max_degree > MAX_INITIAL_DIRS:
        print(
            f"ERROR: max degree {max_degree} exceeds initial_dirs slot count {MAX_INITIAL_DIRS}.",
            file=sys.stderr,
        )
        return 1

    source_url = PRIMARY_URL
    rust_source = generate_rust_source(entries, source_url)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rust_source, encoding="utf-8")
    size_kb = OUTPUT_PATH.stat().st_size / 1024
    print(f"Written {OUTPUT_PATH} ({size_kb:.1f} KB, {len(entries)} entries).")

    return 0


if __name__ == "__main__":
    sys.exit(main())
